includes/functions.php

I think better to use `get_avatar_url` hook instead of `get_avatar`, so when a user or theme calls `get_avatar_url()` function that will return our modification url. 
This would work well for `get_avatar()` function.
@see https://github.com/WordPress/WordPress/blob/master/wp-includes/pluggable.php#L2497

Change avatar modification to use  instead of

---

classes/template-shortcodes.php
dokan.php

The shortcode class Dokan_Template_Shortcodes was inside the is_user_logged_in() function that's why the "dokan-best-selling-product" shortcode wasn't working when the user is not logged in.
And also I returned early for this dokan-my-orders shortcode as the main Dokan_Template_Shortcodes class is outside the is_user_logged_in() function.

Shortcode is not working is fixed #137

---

includes/order-functions.php

feat(*): Adding filter dokan_get_seller_amount_from_order_array
Allow third party plug-ins to correct the individual amount of shipping and tax. Will help correct Dokan Pro's statement table adding shipping twice to the balance as well.

feat(*): Adding filter dokan_get_seller_amount_from_order_array

---

assets/js/dokan.js
assets/src/js/product-editor.js
classes/template-withdraw.php
templates/dashboard/dashboard.php
templates/dashboard/edit-account.php
templates/dashboard/orders-widget.php
templates/dashboard/sales-chart-widget.php
templates/global/no-permission.php
templates/orders/orders-status-filter.php
templates/products/listing-filter.php
templates/products/listing-status-filter.php
templates/products/products-listing.php
templates/withdraw/header.php

Fixed typos in the files where it was Dahsboard instead of Dashboard.

fix typo - all the instance of Dahsboard to Dashboard

---

includes/class-order-manager.php

The issue was when a sub order is created the total_sales count is increased by twice and when the order status is changed to on-hold, processing or completed, the total_sales count again increased by twice.
Reason: When there is a change of order status WooCommerce does update 'total_sales' post meta by order quantity and also keep track whether it has been recorded into database or not by using '_recorded_sales' post meta.
In dokan when an order is placed with products from multi-vendors it creates sub-orders. WooCommerce updates the 'total_sales' post meta for the parent order only and when there is a change of order status of sub order it does update 'total_sales' post meta again cause it didn't update 'total_sales' and '_recorded_sales' post meta.

fix(total_sales_count): the total sales for each product calculates twice when purchased from multiple vendor is fixed #249

---

templates/products/new-product-single.php

Hi,
Without $post_id parameter dokan_product_edit_after_options action is not usable properly.

Added $post_id parameter to dokan_product_edit_after_options action

---

assets/js/vue-admin.js
includes/admin/class-settings.php
src/admin/pages/Settings.vue

With this changes you can,
1. Validate and throw errors from Dokan Pro using `dokan_after_saving_settings` hook.
2. From now on Vue will update the form field value found from the response. So, for example, if your option has `sanitize_callback => 'absint'` and you're trying to save `-10`, then Vue will set the value to `10` found from the ajax response.
@sabbir1991 @saimonh3

refactor(core): Refactor admin settings saving process

---

includes/class-registration.php

The nonce is already validated via these hooks `woocommerce_process_registration_errors` `woocommerce_registration_errors` So, we no longer need to validate the nonce again inside the `set_new_vendor_names ` && `save_vendor_info` method.

fix: nonce verification issue during checkout is fixed #518

---

includes/class-api-manager.php

Similart to wc()->api->$controller, we can access a Dokan REST
controller using dokan()->api->$controller.

Make Dokan REST controllers globally accessible

---

package-lock.json
package.json

From now on translation inside attributes in vue templates is possible. For example,
```html
<a href="#" :title="__('Link title', 'dokan')">{{ __('Link Text', 'dokan') }}</a>
```
Before this update `__('Link title', 'dokan')` won't be parsed.

Update wp-vue-i18n package version

---

templates/orders/details.php

This exact hook is used inside WooCommerce with 3 parameters. When WooCommerce Product Addons does something with this hook, it produce fatal error.

fix: pass order into woocommerce_order_item_{type}_html hook

---

includes/Privacy.php

Adds support for group_description for privacy exporters which was added in WP5.3 through [WPCoreChangeset#45825](https://core.trac.wordpress.org/changeset/45825) and [WPCoreTracTicket#45491](https://core.trac.wordpress.org/ticket/45491)
Update Suggested Privacy Policy text to utilize privacy-policy-tutorial css class instead of wp-policy-help as it was deprecated. Also wrap the contents in the wp-suggested-text div to style the section to match WordPress. This follows from [WPCoreTrac#49282](https://core.trac.wordpress.org/ticket/49282) and although back-compat is being introduced in WP5.4 as of [WPChangeset#47112](https://core.trac.wordpress.org/changeset/47112) this change will better support users of WP5.1-5.4
This also removes the wrapping <div contenteditable="false"> as it's now …

Added Group Description to Exporters and updated Privacy Policy guide to drop use of deprecated classes

---

includes/Admin/SetupWizard.php

Both admin and shop manager wants to see the setup wizard. The dokan-setup page has been registered like this.
```php
add_submenu_page( null, '', '', 'manage_woocommerce', 'dokan-setup', '' );
```
So admin can't see the page if WooCommerce has't been installed before and if we change the cap to `manage_options` then shop manager can't see the setup wizard.

fix: admin is unable to see the setup wizard on new dokan installation is fixed #783

---

includes/Vendor/Manager.php

For backward compatibility we'll allow both `enable_tnc` and `toc_enabled` to set store trams and condition settings.
**Actual Issue:**
--------------
If the admin edit a vendor from the backend the store page terms and condition disappear and the vendors need to set it again.

fix: allow both enable_tnc and toc_enabled to set store trams and condition settings

---

includes/Withdraw/functions.php

'$vendor_id' - should be pass on the filter -  'dokan_get_seller_active_withdraw_methods'  on function - dokan_get_seller_active_withdraw_methods().
Otherwise it's not possible to approve vendor's payment from admin panel while using the filter to add additional payment methods.

Fix: Add Filter parameter on functions.php to approve vendor's withdraw from admin for custom payment methods

---

includes/Order/Manager.php

The current order manager cache implementation is not working, as it does not take many of the arguments into account. I have replaced it with a simpler and non-manual cache key generator that will work for any set of parameters.

Fix order manager caching

---

includes/Order/functions.php

fix(Order): filter out empty seller ids
Fixes a bug where empty Seller IDs were returned by dokan_get_sellers_by.

Updated order functions.php in includes

---

includes/Admin/Settings.php
src/admin/components/Fields.vue
src/admin/components/RefreshSettingOptions.vue
src/admin/pages/Settings.vue
src/utils/Bootstrap.js

This feature is introduced to refresh the Profile options in upcoming Vendor Analytics admin settings. If we have any settings that requires data from external API, then we should fetch that data once, save in options table and use that every page refresh. This refresh feature comes handy when we want to refresh/refetch the external data.
```php
<?php
class MySettings {
public function __construct() {
add_filter( 'dokan_settings_sections',  [ $this, 'add_settings_section' ] );
add_filter( 'dokan_settings_fields',  [ $this, 'add_settings_fields' ] );
/**
* @see "dokan_settings_refresh_option_{$section}_{$field}" filter 
* in \WeDevs\Dokan\Admin\Settings::refresh_admin_settings_field_options()
*/
add_filter( 'dokan_settings_refresh_option_dokan_SECTION_NAME_FIELD_NAME',  [ $this, …
```

Add system to refresh options for select fields in admin settings

---

includes/Commission.php

Enable `dokan_get_processing_fee` filter hook callback to calculate payment gateway fee for sub-orders as well.
Required to fix Dokan Pro support ticket #124441.

fix: Ensure sub-orders also get the correct payment gateway fee (if any)

---

includes/Withdraw/Hooks.php

Reference: Dokan Pro support ticket #338760.
This PR fixes the bug that occurs because Dokan did not use proper cache behavior :
1. used wrong cache group & cache key
2. did not flush the relevant cache entries after balance was updated

fix: Bug fix for "Withdrawal current balance is incorrect"

---

includes/Vendor/Vendor.php

This cache key produces wrong report when cache is enabled. Made it dynamic so when we get balance of a specific date it stores only for that date.

fix: vendor balance cache key updated

---

package-lock.json
package.json
src/admin/main.js
src/admin/pages/Vendors.vue
src/admin/pages/Withdraw.vue

* vue wp list table package updated to 1.3.0
* add translation support for list tables
* global method `listTableTexts` for list table texts

fix: missing translations for admin dashboard

---

includes/Rewrites.php

It conflicting with Divi theme when use custom Divi builder templates and then happen template_include filter hook priority issue

fix: Store and store TOC template make high priority

---

includes/Vendor/Vendor.php

If the vendor has a rounded value in their balance then you are unable to request for a withdrawal of the full amount as it shows an error.
Fix: #1030

Fix: vendor withdraw balance

---

includes/REST/OrderController.php

When an order data is retrieved using `.../wp-json/dokan/v1/orders/` the "total" order value is rounded. One the other hand, WooCommerce's response shows the correct value.
Fix: #941

Fix: REST API order total value gets rounded

---

includes/Dashboard/Templates/Products.php

Dokan’s integration with WC Subscription plugin does not allow the vendor to create downloadable/virtual products in the dashboard.
Fix: https://github.com/weDevsOfficial/dokan-pro/issues/749

Enhancement: enable downloadable and virtual for subscription product

---

includes/Dashboard/Templates/Settings.php

Hi,
This PR solves the "Vendor Dashboard Store" settings save error. code extracted from #1098 
The error is below.
```
2021-02-19T10:24:36+00:00 CRITICAL Uncaught TypeError: Cannot access offset of type string on string in /Users/shohag/Sites/wd/wp-content/plugins/dokan-lite/includes/Dashboard/Templates/Settings.php:504
Stack trace:
#0 /Users/shohag/Sites/wd/wp-content/plugins/dokan-lite/includes/Dashboard/Templates/Settings.php(267): WeDevs\Dokan\Dashboard\Templates\Settings->insert_settings_info()
#1 /Users/shohag/Sites/wd/wp-includes/class-wp-hook.php(287): WeDevs\Dokan\Dashboard\Templates\Settings->ajax_settings('')
#2 /Users/shohag/Sites/wd/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#3 /Users/shohag/Sites/wd/wp-includes/plugin.php(484): …
```

fix: on save store settings error fix

---

includes/Order/functions.php

Issue Description:
Vendors are unable to export orders for specific order status. Vendors can see orders from different order statuses from their dashboard but there is no way to export those. The export filtered button only works for the date and customer filter.
How to reproduce:
Navigate to vendor dashboard > orders page
Click on any of the order statuses
Click on export filtered
A blank CSV is exported
Expected behavior:
The export filtered button should export all orders which are available under that certain order status - https://prnt.sc/y6o4w8
Versions:
WP - 5.6
WC - 4.9.2
Dokan Lite - 3.2
Dokan Pro - 3.2

fix: filtered order export on vendor dashboard

---

includes/Product/Manager.php
includes/Rewrites.php

If the product post_date field value is the same for a couple of products, orderby parameter is not working and  Some products are showing 2x/3x and some are not showing in the store page and vendor dashboard product page

fix: fixes store/product orderby parameter for query

---

includes/functions.php

Issue from Facebook  post:
> Can someone help me with the time zone of the stores? In my timezone (GMT-3) between 20 and 24 hours the stores appear closed even though they are open. I had solved it with this code https://wordpress.org/support/topic/time-26/page/2/ but I updated Dokan and it stopped working.

fix: fixes dokan store open time timezone mismatch

---

includes/functions.php

There is a different edit URL for the product that has the status of published.
Removed the status check and set the URL with the vendor dashboard prefix.
fix #1114

fix: different edit url for different product status

---

includes/functions.php
templates/settings/store-form.php

fixes https://github.com/weDevsOfficial/dokan-pro/issues/1167

fix: time format with forward slash (\) wasn't parsing correctly on store open/close time dropdown

---

includes/Product/Manager.php
includes/Product/functions.php

There are some redundant product fields check for updated events. for this, in quick edit, we losses some of the product data not currently being updated.

refactor: product create update redundant check

---

src/admin/pages/VendorAccountFields.vue

In the admin area, when the admin tries to add a new vendor using vendor wizard, The store URL shows uppercase letter.

fix: capitalize vendor url in add new vendor

---

includes/Shortcodes/Stores.php

Dokan stores shortcodes allow new 4 attributes:
**Store Category wise:** `[dokan-stores category="clothing"]
`**Order wise:** `[dokan-stores order="ASC"]
`**Orderby wise:** `[dokan-stores orderby="registered"]
`**Store_id wise:** `[dokan-stores store_id="1, 2, 3"]`
reference issue: https://github.com/weDevsOfficial/dokan-pro/issues/1017

update: Store list shortcode enhancement #1017

---

includes/functions.php

https://github.com/weDevsOfficial/dokan/issues/1170

Fix malformed store URL when the home URL contains a query parameter

---

includes/functions.php

Product count is displaying count number including `product_type = booking` in this PR booking product are excluded.
fix: https://github.com/weDevsOfficial/dokan-pro/issues/1229

Fix: product count exclude booking product

---

composer.json
composer.lock
includes/functions.php

Solves https://github.com/weDevsOfficial/dokan/issues/1172.
I added a preliminary commit to include the [jakeasmith/http_build_url](https://packagist.org/packages/jakeasmith/http_build_url) composer package. This is a very popular package that provides an implementation of `http_build_url` if the function does not already exists. It makes easy and safe to handle URLs.

Fix malformed dashboard subpage URL when `page_link` is filtered to add a query parameter

---

includes/Dashboard/Templates/Orders.php

Process to create custom order export using this hook : 
1) Override date-export.php template in child theme /wp-content/themes/your-theme/dokan/orders/date-export.php : add input submit with custom name
2) Use the new hook to create custom function like in this file (line 113 to 127)
3) Create a custom function to replace 'dokan_order_csv_export'
I'm using this method to generate custom CSV to export orders to the shipping web app Packlink PRO.
Thanks.

New hook: vendor dashbrd custom CSV orders export

---

includes/wc-functions.php

This pr fix Decimal as comma-separated sale price comparison with regular price.
fix: https://github.com/weDevsOfficial/dokan/issues/1176

fix: Decimal as comma separated sale price does not save

---

includes/Product/functions.php

This pr handles the issue with variation pagination display for the variable product with type Pending Review.
fix: https://github.com/weDevsOfficial/dokan-pro/issues/1244

fix: product variation pagination display for variable product with type Pending Review

---

includes/functions.php

Transposition of initial PR on our fork (https://github.com/OnTheGoSystems/dokan/pull/2).
- Introduced a new function `dokan_add_subpage_to_url` to avoid the
repetitive issues due to incorrect path concatenation.
- Added- the new subpage argument in the filter hook.
https://github.com/weDevsOfficial/dokan-wpml/issues/13

Extend the function `dokan_get_page_url` to accept `$subpage` as an extra parameter

---

includes/Ajax.php
templates/orders/details.php

that can be done by show dokan-order-status-form in devtool and change status easily, because "dokan-order-status-form" form always printed even if we change "order_status_change" option to false, that cause to generate a valid nonce too.

Fixed a bug that would allow vendors to change order status even if they don't have permission to do so

---

includes/Emails/Manager.php

This PR adds some email templates to `dokan_email_list` filter list.
Fix: https://github.com/weDevsOfficial/dokan/issues/1181

fix: email template override for dokan vendor completed order

---

includes/Abstracts/DokanRESTController.php
includes/REST/ProductController.php

Add support to force parameter on API requests.
Use false as default because backward compatibility.
Closes #1202

feat(api): Add support to send objects to trash

---

templates/products/new-product.php

`dokan_product_gallery_image_count` action hook added to give support for Product Gallery image set restriction in **Add new Product** page.
The hook is already present in Product edit page and add new product popup
for more info please check [this PM task](https://lounge.wedevs.com/wp-admin/admin.php?page=pm_projects#/projects/39/task-lists/1754/tasks/54310)

fix: dokan_product_gallery_image_count action added

---

assets/src/js/product-editor.js

When we add a new attribute for a variable product, the tag's select 2 ajax search is being broken.
In this PR we have added `Dokan_Editor.bindProductTagDropdown();` in `Dokan_Editor.attribute.addNewAttribute`
For more info please check [this link](https://lounge.wedevs.com/wp-admin/admin.php?page=pm_projects#/projects/39/task-lists/1754/tasks/54813).

fix: Product tag search not working in variable product after adding new attribute

---

assets/src/js/product-editor.js

This PR adds a check if **this product need shipping** is checked and virtual check box is also checked, then we are unchecking shipping checkbox.
Please run `grunt` command.
fix: https://github.com/weDevsOfficial/dokan-pro/issues/1179

fix: display shipping widget though virtual checkbox selected

---

includes/REST/StoreController.php
includes/Vendor/Vendor.php
includes/Widgets/StoreCategoryMenu.php
includes/functions.php
includes/template-tags.php
includes/wc-functions.php

new: added a new method named get_published_products() under Vendor class to get all published products of a vendor
new: added a new method named get_store_categories() under Vendor class to get all published products assigned categories
new: added get_best_selling_products() method under Vendor class
new added best selling products category support under get_store_categories() in Vendor class
update: rewritten store category dokan_store_category_menu() function
REST API:
new: added a new rest route name id/categories under StoreController to get corresponding vendors published product categories (wp-json/dokan/v1/stores/3/categories)
new: added popular category support under StoreController rest API (wp-json/dokan/v1/stores/3/categories?best_selling=1)

New Rest Route To Get Corresponding Vendors Product Categories Under StoreController

---

includes/wc-functions.php

**Fix:** Downloadable file was unable to be removed when there only one file exists
fixes https://github.com/weDevsOfficial/dokan/issues/1282

Fix #1282 : unable to remove downloadable file

---

includes/Admin/Settings.php

new filter `dokan_settings_withdraw_order_status_options` added.
Fix: https://github.com/weDevsOfficial/dokan/issues/1295

update: filter added for Order status list allowed for withdrawal

---

includes/Dashboard/Templates/Orders.php
includes/functions.php
templates/orders/date-export.php

**description**: when managing permissions for staff, the vendor will get a new option 'Export product' under the 'order' section. Staffs with this permission can export the order list as csv file.
1. new array element added in $capabilities array in includes/functions.php
2. 'dokan_export_order' capability check added before the export buttons and also in the action. capability check added so that vendor and staff both can view the buttons.
fix #1247 
Dokan Pro PR: https://github.com/weDevsOfficial/dokan-pro/pull/1500
Note: the previous PR is closed because the upgrader file is moved from lite to pro. Previous PR: #1322

fix: Export order permission for staffs

---

assets/js/dokan.js
assets/src/js/product-editor.js
includes/Assets.php
includes/Dashboard/Templates/Products.php
includes/Product/functions.php
templates/products/tmpl-add-product-popup.php

Previously, vendor could add unlimited tags on his/her product in add, edit product.
But now I have added a new filter called `dokan_maximum_tags_select_length` by which maximum tag addition number can be changed. 
Also added validation in frontend and backend for maximum tag add and edit
frontend validation: https://prnt.sc/1s8veg8
Backend validation: https://prnt.sc/1s8vspn
fixes #1236 Similar code fix in dokan pro https://github.com/weDevsOfficial/dokan-pro/pull/1471

feat: Set limitation for how many product tags that vendor can input

---

templates/orders/details.php

This is simple changes, but we need add this changed on this release @nurul-umbhiya vai

fix: Added missing param on woocommerce_admin_order_item_headers

---

includes/Product/functions.php
includes/wc-template.php

Allow filter dokan_get_vendor_by_product preventing the addition of the "Vendor" cart-item tag if it doesn't return a valid vendor
Fixes: #1400

Fix[Product]: allow filter to prevent adding cart-item tag

---

templates/settings/store-form.php

There is a setting in Customizer "Hide email address". If the admin checks this setting checkbox, the vendor should not see the "Show email address in store" option on the vendor setting page.

Render vendor email setting option conditionally

---

assets/src/js/product-editor.js

This is an enhancement for the Dokan auction module. There is no support for downloadable and virtual product for the auction product. This enhancement was requested on the Dokan pro. And there is some issue related to the Dokan lite. So here is the fix for that. 
Related pr in dokan pro: https://github.com/weDevsOfficial/dokan-pro/pull/1546
fix https://github.com/weDevsOfficial/dokan-pro/issues/1112

Fix downloadable virtual product support for auction module

---

includes/Admin/Settings.php

We need a Google Maps API key for distance rate shipping. That's why Google Maps and Mapbox are now always visible on Dokan admin setting page.

new: Google map and maxbox make always visible

---

assets/src/js/helper.js
assets/src/js/script.js
includes/Admin/Settings.php
includes/Ajax.php
includes/Assets.php
includes/Widgets/StoreContactForm.php
includes/functions.php
templates/widgets/store-contact-form.php

Previously, there was no captcha checking on store page contact form.
Now, Google reCaptcha checking is integrated to store contact form.
Also, added reCaptcha site key input field on the `Dokan->Settings->Appearance` admin menu. Screenshot: https://imgur.com/VNdgSCj

enhance: recaptcha integration to store contact form

---

templates/emails/product-published.php

Vendor product published mail greeting "Hello" made translatable.
Suggestion for QA: 
1. Make string translatable by WPML or other translatable string plugins to your local language.
2. Configure your mail settings by the WP Mail SMTP plugin or using your preferred plugin.
3. Add a new product from the vendor dashboard.
4. Publish that product from the admin dashbaord.
5. See your mail greeting "Hello" is translated to your local?
Fixes: #1513

Make Hello text translatable.

---

includes/Rewrites.php

If users enter [wrong store name on search bar](https://prnt.sc/26ezyt0) getting the error Trying to get property 'data' of non-object and Trying to get property 'ID' of non-object.

Fix: handle store not found exception

---

includes/REST/StoreController.php

Usage: `http://dokan.test/wp-json/dokan/v1/stores/<store_id>/products?per_page=20&page=2`

Added per_page and page param support on store products rest api

---

includes/Withdraw/Manager.php
includes/Withdraw/functions.php
src/admin/components/Fields.vue
src/admin/pages/Withdraw.vue
templates/settings/payment.php
templates/withdraw/approved-request-listing.php
templates/withdraw/cancelled-request-listing.php
templates/withdraw/pending-request-listing.php

Now admin can add custom withdrawal methods for their vendors from the Dokan admin settings [under withdraw section](https://prnt.sc/26c4ku2). Then vendors can set their custom payment option from the vendor dashboard under [the payment menu](https://prnt.sc/26c4ljz). And then they can select withdrew method from [their withdrawal section](https://prnt.sc/26c4mfw). After sending withdrawal request check custom payment info show both [vendor](https://prnt.sc/26c4ojo) and [admin dashboard](https://prnt.sc/26c4osk). Finally, deactivate Dokan PRO and check have no issue.
PRO Pull: [#1686](https://github.com/weDevsOfficial/dokan-pro/pull/1686)

Added custom withdraw method option

---

includes/Dashboard/Templates/Products.php

Issue: https://github.com/weDevsOfficial/dokan-pro/issues/1301
Before,
In the vendor dashboard single product edit page if the vendor sets the product type as a subscription product and doesn't check on the virtual checkbox it is auto check-in after saving the product and it never updates. Also, the shipping box does not show and hide properly based on the virtual checkbox.
Now,
Virtual checkbox data is updating properly and the shipping box showing and hiding properly based on the virtual checkbox.
Fix: https://github.com/weDevsOfficial/dokan-pro/issues/1301

variation virtual product auto checked fixed

---

assets/vendors/select2/select2.css

Issue: #1483
Before,
There was a select mistake.   .select2-container .select2-selection--single { height: 33; }
Now,
The height unit is in px like, .select2-container .select2-selection--single { height: 33px; }
FIx: #1483

fix select2 container, select2 section single height 33 to 33px

---

includes/Order/Hooks.php

Fixes crash when creating an order using the woocommerce API with coupon lines.
```
[03-Dec-2021 15:32:20 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_cart() on null in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/dokan-lite/includes/Order/Hooks.php:284
Stack trace:
#0 /Applications/MAMP/htdocs/wordpress/wp-includes/class-wp-hook.php(303): WeDevs\Dokan\Order\Hooks->ensure_vendor_coupon(true, Object(WC_Coupon), Object(WC_Discounts))
#1 /Applications/MAMP/htdocs/wordpress/wp-includes/plugin.php(189): WP_Hook->apply_filters(true, Array)
#2 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/woocommerce/includes/class-wc-discounts.php(962): apply_filters('woocommerce_cou...', true, Object(WC_Coupon), Object(WC_Discounts))
#3 …
```

fix(Order): create order API with coupon lines

---

includes/Emails/VendorCompletedOrder.php
includes/Emails/VendorNewOrder.php

Changed the callback function return value of `woocommerce_email_enabled_new_order` filter 
Closes #1597 
1.Woocommerce > Settings > Email Tab > Disable New order email
2. Create an Order
3. Check if the email is sent to the admin
> **fix:** Stop sending new order emails to selected recipients (including admin) when the New Order email is disabled in Woocommerce Settings
* Grammar …

fix New Order email send to admin even if this email is not enabled in WC settings

---

templates/settings/payment.php

make static payment settings urls to dynamic urls
Closes #1609
1. please consult the related issue
2.
3.
> **fix:** payment settings page 404 if dashboard url slug is changed

fix payment settings page 404

---

includes/Dashboard/Templates/Settings.php
templates/settings/bank-payment-method-settings.php
templates/settings/payment-manage.php
templates/settings/payment.php

used `dokan_get_navigation_url` instead of `dokan_get_page_url` to get the links
Closes [Dokan Pro issue 1907](https://github.com/weDevsOfficial/dokan-pro/issues/1907) .
1. Please follow the linked issue
> **fix:** WPML translated endpoint not working in payment settings page

fix dokan payment settings doesn't support wpml translated links

---

assets/css/style.css
assets/src/less/store.less

The third store header has broken title styling that causes overlap
Simple Style Fix to Store Header
Closes https://github.com/weDevsOfficial/dokan/issues/1625.
Ensure the third store header is chosen and view vendor store page
- fixed third store header styling
> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

style fix broken third store header template

---

assets/src/js/product-category-ui.js
includes/ProductCategory/Categories.php
includes/ProductCategory/ProductCategoryCache.php

Closes #1669
1. Install WPML and check if the multistep categories are shown as the selected language, should not show all language categories.
> Fix: wpml support in the multistep product category.
> As a contributor, …

Show multistep categories as language selected by wpml

---

includes/REST/OrderController.php

In this PR, we've added after and before filter in order list API -
```sh
dokan/v1/orders?after=2022-10-01&before=2022-10-30
```
> Order list Rest API support after-before date filter.

Enhancement: Order REST API date filter - after/before

---

includes/Admin/SetupWizard.php

Conditionally removing Custom Withdrawal method from Setup Wizard. This Closes https://github.com/weDevsOfficial/dokan-pro/issues/1923
1. Please check the issue https://github.com/weDevsOfficial/dokan-pro/issues/1923
**update**: conditional rendering custom withdrawal method in the admin setup wizard.
As we know, the custom withdrawal method needs not only to enable the method but also to populate the method name and method type. And as in the Settings wizard, we are not populating the method name and type, the method is not enablable. 
If Admin previously saved those values only then the custom withdrawal method is displayed and can be activated.
* Code is not following code style …

fix: Custom Withdrawal method enabling and display conditional restriction

---

templates/whats-new.php

Update What's New For Version 3.7.24

---

includes/Admin/SetupWizard.php
templates/admin-setup-wizard/step-store.php

* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2564 .
1. check issue https://github.com/weDevsOfficial/dokan-pro/issues/2564
no changelog needed
> As a contributor, your responsibility is to learn from …

update: shipping tax fee recipient setting added in admin setup wizard

---

includes/functions.php

* Closes #1965.
1.
2.
3.
> new: Filter hook to the store URL getter method
> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to …

🪝 new: Filter hook to the store URL getter method

---

includes/Rewrites.php

Fix: Dokan Filter Products by Attribute Widget Not Working for Multi-Word Attributes.
Closes #2018
1. Test as described and given video in the issue.
>Fix: Dokan filter products by attribute widget not working for multi-word attributes. …

Fix: Dokan Filter Products by Attribute Widget Not Working for Multi-Word Attributes.

---

templates/store-header-times.php

* Closes https://github.com/getdokan/dokan-pro/issues/2738
* Please follow the steps from https://github.com/getdokan/dokan-pro/issues/2738
> fix: Invalid store opening or closing times generate warning and fatal error on single store pages …

🎯 fix: Invalid store opening or closing times generate warning and fatal error on single store pages

---

includes/Dashboard/Templates/Products.php
includes/Emails/ProductPublished.php
includes/functions.php

* Closes #2021.
* Please follow the status from #2021.
> fix: Product edit link on email template redirects to the products listing instead of single product edit page
> As a contributor, your responsibility is to learn …

🎯 fix: Product edit link on email template redirects to the products listing instead of single product edit page

---

includes/Product/Hooks.php

* Moved code from pro https://github.com/getdokan/dokan-pro/pull/2806
* closes: https://github.com/getdokan/dokan-pro/issues/2782
update: display Not purchasable notice for own product …

update: display Not purchasable notice for own product

---

includes/Order/functions.php

Getting a fatal error while trying to edit a WooCommerce Subscription under WordPress Admin Dashboard --> WooCommerce --> Subscriptions menu
```
2023-11-30T08:34:07+00:00 CRITICAL Uncaught Error: Call to a member function get_id() on int in /var/www/html/app/wp-content/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php:412
Stack trace:
#0 /var/www/html/app/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/data-stores/class-wcs-subscription-data-store-cpt.php(309): WC_Order_Data_Store_CPT->get_total_tax_refunded()
#1 /var/www/html/app/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(224): WCS_Subscription_Data_Store_CPT->get_total_tax_refunded()
#2 /var/www/html/app/wp-content/plugins/woocommerce/includes/class …
```

[WooCommerceSubscription] Fixed a fatal error while trying to edit a subscription

---

includes/Order/Hooks.php

* Full PR Link
* Closes #
No change log needed
> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive …

fix: Vendor getting draft order in dashboard

---

includes/Emails/VendorProductReview.php

* Full PR Link
* Closes https://github.com/getdokan/dokan/issues/2206
```
- **fix:** product review email cannot be disabled without also disabling Contact Vendor email
```
> As a …

fix: product review email cannot be disabled without also disabling Contact Vendor email

---

assets/src/js/vendor-registration.js
includes/Assets.php
includes/template-tags.php

* Full PR Link
* Closes https://github.com/getdokan/dokan/issues/2203
```
- fix: under wooCommerce my-account registration section, `I am a customer` was forced to be set as the default value. With this PR this problem has been fixed.
- new: added a new filter to set a default value for I am a customer / I am a vendor radio button.
```
* Code that is not readable: too many nested 'if's are a bad …

fix: under wooCommerce my-account registration section, `I am a customer` was forced to be set as default value

---

assets/src/less/dashboard.less
assets/src/less/extra.less
assets/src/less/responsive.less

* Full PR Link
* Closes [#2054](https://github.com/getdokan/dokan/issues/2054)
* Enable anlytics module & go to vendor dashboard analytics menu.
* Open menu tabs on responsive mood.
```
Fix: Responsive issue on vendor dashboard tabs preview.
```
**Storefront Theme Preview :**
**BuddyBoss Theme Preview :**
**BuddyBoss Theme Preview :**
**Storefront Theme Preview :**
* Code that is not readable: too many nested 'if's are a …

fix: Responsive issue on vendor dashboard tabs preview.

---

templates/emails/plain/new-seller-registered.php
templates/emails/plain/reverse-withdrawal-invoice.php
templates/emails/plain/vendor-completed-order.php
templates/emails/plain/vendor-new-order.php
templates/emails/plain/vendor-product-review.php
templates/emails/product-published.php
templates/emails/reverse-withdrawal-invoice.php
templates/emails/vendor-completed-order.php
templates/emails/vendor-new-order.php
templates/emails/vendor-product-review.php
templates/my-orders.php
templates/reverse-withdrawal/transaction-listing.php
templates/store-lists-filter.php
templates/sub-orders.php
templates/vendor-store-info.php

* Full PR Link
* Closes #
No changelog is needed. …

refactor: `WordPress.Security.EscapeOutput.OutputNotEscaped` escaping

---

docs/feature-override/readme.md
includes/Assets.php
includes/DependencyManagement/Providers/CommonServiceProvider.php
includes/VendorNavMenuChecker.php
includes/functions-dashboard-navigation.php
src/Dashboard/index.tsx
src/Dashboard/tailwind.scss
tests/php/src/VendorNavMenuCheckerTest.php

* Full PR Link
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/105
*Title*
* …

update: Vendor dashboard menu override for react templates based on Template override conditions

---

docs/api/api.md
includes/Abstracts/DokanBaseRESTController.php
includes/Abstracts/DokanRESTAdminController.php
includes/Abstracts/DokanRESTBaseController.php
includes/Abstracts/DokanRESTCustomerController.php
includes/Abstracts/DokanRESTVendorController.php

* Full PR Link
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/180
*Title*
* …

enhance: Seperate dokan rest controller for role-wise API implementation.

---

includes/Commission/OrderCommission.php

* Closes https://github.com/getdokan/dokan-pro/issues/4395
```
- **fix:** Added number value data type casting in order commission.
```

Fix ensure shipping fees are calculated as floats in OrderCommission

---

tests/pw/pages/selectors.ts
tests/pw/tests/e2e/shop.spec.ts

Changed the category selector in selectors.ts to use '#dokan-geo-product-categories-root'. Commented out the category filter test in shop.spec.ts with a note to re-enable when the feature is implemented in WooCommerce.
* Full PR Link
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/852
*Title*
* DRY: Don't …

Update category selector and skip category filter test
