- includes/order-functions.php
Added a filter `dokan_get_seller_amount_from_order` for seller net amount changing
> Added dokan_get_seller_amount_from_order filter

- templates/settings/payment.php
> Updated payment.php

- classes/installer.php
- classes/upgrade.php
- dokan.php
- includes/upgrades/dokan-upgrade-2.7.6.php
> Changed ip column data size for withdraw table for compatibility with IPv6 and added the updater is fixed #140

- classes/admin-user-profile.php
- includes/admin-functions.php
Admin can edit user store URL from backend user profile edit.
> add store URL field in user edit form

- classes/ajax.php
we don't need to inject anything on the checkout page as everything is already there by default.
> Vendor name is showing twice on the cart checkout page is fixed #170

- templates/global/product-tab.php
I needed to add these hook to add content on the product tab from the other module
> feat(product-tab): add action_hook on product tab so that we can add content on the product tab as needed

- templates/seller-search-form.php
- templates/store-lists.php
1. Added filter to toggle seller search form.
2. Added actions hooks before and after seller listing loop.
> Add filter and actions hooks in seller listing page

- assets/js/vue-admin.js
- src/admin/components/Fields.vue
Enable option group for select fields in admin settings panel
> feat(core): Enable option group for select fields in admin settings

- includes/class-order-manager.php
- includes/order-functions.php
Hello,
We have added new filter and action hooks those are very useful in our project,
Please check and implement them.
Thanks
> Added new action and filter hooks

- includes/class-vendor.php
To retrieve product of a particular vendor we can use it like this: 
`dokan()->vendor->get( $vendor_id )->get_products(); `
> feat: add get_products method in vendor class

- classes/tracker.php
- dokan.php
- lib/appsero/Client.php
- lib/appsero/Insights.php
- lib/appsero/License.php
- lib/appsero/Updater.php
Update Appsero SDK to latest
Fix conflict with WP User Frontend
> Update appsero SDK

- includes/class-order-manager.php
Split the order when the order containing products from multiple vendors is created from the admin dashboard.
> Split orders in admin dashboard.

- templates/orders/details.php
filter or action is required to do changes by hooks if someone is creating new plugin or customizing core functionalities !
> filter is required here to do custom modification

- assets/src/less/setup-no-wc.less
- includes/functions.php
- templates/admin-setup-wizard/step-no-wc-introduction.php
> refactor: show notice in dokan admin setup wizard if minimum PHP version is not met for WooCommerce

- includes/Ajax.php
Hoook name: dokan_withdraw_export_csv_args
> Add a filter hook on withdraw export csv args

- includes/Dashboard/Templates/Orders.php
- includes/Emails/Manager.php
- includes/Emails/VendorNewOrder.php
- includes/functions.php
- templates/emails/plain/vendor-new-order.php
- templates/emails/vendor-new-order.php
Need to first test it before merge.
> Fix: New order email for vendor is showing admin URL issue fixed #732

- templates/emails/vendor-new-order.php
Fixes:
- TAX details show on vendor order email
- Product addon information show on vendor order email
> Fix - Vendor order email does not have the TAX details issue fixed #809

- includes/Admin/Settings.php
- includes/Order/Hooks.php
> feat: exclude cash on delivery payments from vendor withdrawal balance

- includes/Ajax.php
Now with the notes will insert author email id
> Fix - Order notes in vendor dashboard worng insert author data

- includes/Admin/Hooks.php
> fix namespace WC_Order

- assets/src/less/products.less
vendors weren't able to change or delete their product featured image
> fix: css conflicting with the YITH Badge Management Plugin

- templates/settings/store-form.php
> Fix:  phone field pasting option enabled

- includes/Admin/Hooks.php
fix: pre_get_post hook remove from admin/hook fixed #859
> Fix: i-859 pre_get_post hook remove from admin/hook

- includes/REST/AdminDashboardController.php
It happens due to WP 5.5 added some changes in `SimplePie::get_links` method. @sabbir1991 @FaraziF please test for before and after WP 5.5 versions.
You need to clear the transient with the hash `33dfe3053f180bedc95ae6d74eea5ed4`
> Fix admin dashboard feed REST Request error

- includes/Rewrites.php
> fix: redirect to 404 if vendor do not exist for toc template

- includes/Vendor/Manager.php
> fix: vendor created by admin shows in search result

- includes/REST/StoreController.php
> fix: search store by store name

- includes/Order/functions.php
fix - fixed Order fetching issues with REST API #818 originally developed by @zamandevs
I needed to resubmit this or due to a merge conflict on my commit.
> fix - fixed Order fetching issues with REST API #818 originally developed by @zamandevs

- includes/REST/StoreController.php
> fix: store search with meta query

- includes/Order/Hooks.php
- templates/orders/details.php
> fix: stock level wrong calculation on order note

- includes/Admin/AdminBar.php
- includes/functions.php
> Feature: added “Visit Vendor Dashboard” link to adminbar

- includes/REST/StoreController.php
- includes/Vendor/Manager.php
> fix: vendor search for disable vendor

- src/admin/pages/Settings.vue
added searching option in dokan admin settings.
https://user-images.githubusercontent.com/9963909/102743638-0d20e080-4382-11eb-858c-060f311a8706.mp4
> feat: searching option in dokan admin settings

- .editorconfig
- assets/css/style.css
- assets/js/dokan.js
- assets/src/js/script.js
- assets/src/less/extra.less
- assets/src/less/form.less
- assets/src/less/general.less
- assets/src/less/products.less
- assets/src/less/responsive.less
- assets/src/less/settings.less
- assets/src/less/site-navigation.less
- includes/Product/functions.php
- templates/orders/listing.php
- templates/products/listing-filter.php
- templates/products/products-listing-row.php
- templates/products/products-listing.php
- templates/settings/store-form.php
> Responsive dashboard product and order table

- includes/template-tags.php
Handle error after fetching terms
> fix: error handling in store product category not showing properly

- includes/Product/functions.php
> fix: product function error

- includes/Registration.php
> fix: filter for $allowed_roles in vendor registration is missing

- includes/Ajax.php
> fix: Downloadable product "Grant Access" JS error Fixes #1017

- assets/src/less/store-lists.less
- assets/src/less/store.less
- templates/store-lists-loop.php
**How look the UI:**
**How mange the settings:**
Case 1: This option will show only if Dokan admin setting **Store Opening Closing Time Widget** and vendor setting **Store Opening Closing Time** both enabled 
Case 2: This globally can mange by admin can enable/disable using Dokan admin setting **Store Opening Closing Time Widget**
http://prntscr.com/w6wj18
Case 3: This option can mange by vendor their store only by using vendor setting **Store Opening Closing Time** 
http://prntscr.com/w6wits
> new: Store open and closed status add on dokan store listing page

- includes/REST/StoreController.php
This PR fixes https://github.com/weDevsOfficial/dokan-pro/issues/1008
> fix: vendor pending tab keeps loading

- assets/css/style.css
- assets/js/dokan.js
- assets/src/less/login-form-popup.less
- templates/global/seller-registration-form.php
Radio button should work only when user click mouse cursor on the top of the radio btn.
fix https://github.com/weDevsOfficial/dokan-pro/issues/998
> Fix:Site registration as vendor ghost touch fixes #998

- includes/wc-functions.php
This PR related with dokan pro issue #1049 https://github.com/weDevsOfficial/dokan-pro/issues/1049
> fix: More product tab showing other vendors product issue fixed #1049

- includes/Admin/Settings.php
fixed #1051
https://github.com/weDevsOfficial/dokan-pro/issues/1051
> fix:#1051 Mistake on the writing

- includes/REST/ProductController.php
This PR fix #1092
Also fix the related issue in the DELETE request.
> fix: Unable to update product vai REST API issue fixed #1092

- includes/Upgrade/Manager.php
- includes/Vendor/Vendor.php
- includes/reports.php
- includes/template-tags.php
- includes/wc-functions.php
This PR fix reported warnings below:
```
Deprecated: Required parameter $value follows optional parameter $address in /opt/lampp/htdocs/dokantest/wp-content/plugins/dokan-lite/includes/Vendor/Vendor.php on line 1236
Deprecated: Required parameter $value follows optional parameter $paypal in /opt/lampp/htdocs/dokantest/wp-content/plugins/dokan-lite/includes/Vendor/Vendor.php on line 1247
Deprecated: Required parameter $wp_query follows optional parameter $before in /opt/lampp/htdocs/dokantest/wp-content/plugins/dokan-lite/includes/template-tags.php on line 70
Deprecated: Required parameter $order follows optional parameter $headers in /home/ljuqxxmy/public_html/winklermarket/wp-content/plugins/dokan-lite/includes/wc-functions.php on line 1157
Deprecated: Required parameter $order follows …
```
> fix: PHP 8 warning fix with minimal change

- includes/Ajax.php
- templates/orders/details.php
Hi,
There are multiple nonce fields in the order tracking form.
Nonce and action are not passing correctly.
Fixed #1093
> fix: tracking number save issue fix

- includes/Privacy.php
- includes/Registration.php
- includes/functions.php
- src/admin/pages/AddVendor.vue
- src/admin/pages/VendorSocialFields.vue
> fix: gplus cleaning

- templates/products/inventory.php
Here have related PR on Dokan pro - https://github.com/weDevsOfficial/dokan-pro/pull/1109
> fix: Unable to save stock value for variation product issue fixed #1034

- includes/wc-functions.php
This refactor updates the current SKU handling of products based on current Woocommerce lookup table.
> refactor: updating SKU handling for products

- assets/src/js/script.js
Sales price validation check for subscription product added.
Related #1081
> fix: sale price popup error modal

- assets/src/js/store-lists.js
- templates/store-lists-loop.php
On this PR also fixed this issue https://github.com/weDevsOfficial/dokan/issues/1101
> new: Enter key allow for vendor search on store listing page

- includes/wc-functions.php
> fix: Cancel order email is sent to the vendor

- src/admin/pages/Withdraw.vue
This PR will fix the issue of not showing IBAN Number, Swift Code in admin withdraw request details.
closes #1134
Final Output:
> fix: iban, swift code number not showing in admin withdraw requests

- includes/Dashboard/Templates/Products.php
- includes/functions.php
- includes/template-tags.php
- templates/products/listing-filter.php
- templates/products/listing-status-filter.php
- templates/products/products-listing.php
Vendor product listing page added 2 new filters options
1. Stock wise filter
2. Product type wise filtering
> new: New filters added on vendor product listing page

- includes/Dashboard/Templates/Orders.php
This PR fixes the order export option not filtered the customer filtered data
fixes #1164
> fix: order export not filtered customer filtered data

- templates/store-toc.php
> Fix single store page template layout

- includes/template-tags.php
Replacing https://github.com/OnTheGoSystems/dokan/pull/1 on OTGS fork.
https://github.com/weDevsOfficial/dokan-wpml/issues/12
> Introduce the filter hook `dokan_dashboard_nav_settings_key`

- templates/products/products-listing-row.php
When we visit the product page in the local language the product created date displays the current date instead of the actual published date.
> fix: product published date displaying current date in local language

- includes/Commission.php
update: formate gateway fee with wc_format_decimal function and removed round() function
> fix: delete cache after updating dokan vendor balance table data

- includes/Rewrites.php
- includes/Shortcodes/Stores.php
2 new options added on stores listing short-codes
1. Now we can show the stores which one have at least 1 product, example: `[dokan-stores with_products_only="yes"]`
> New/two new options added with stores listing short-codes

- includes/Ajax.php
- includes/Order/functions.php
- templates/orders/date-export.php
- templates/orders/listing.php
fixes [1245](https://github.com/weDevsOfficial/dokan/issues/1245)
> fixed: vendor order page pagination fixed for date and customer filter

- includes/Admin/Settings.php
- includes/functions.php
Fixes [1179](https://github.com/weDevsOfficial/dokan/issues/1179)
> Fix: error in dokan setting

- includes/Walkers/TaxonomyDropdown.php
fix https://github.com/weDevsOfficial/dokan-pro/issues/1350
> fix: warning in product create page

- templates/products/new-product.php
- templates/products/tmpl-add-product-popup.php
This PR is related to https://github.com/weDevsOfficial/dokan-pro/issues/1334
> update: hide create and add new button if only one product creation allowed

- includes/REST/ProductController.php
> Children IDs not showed on API REST

- includes/Order/Hooks.php
fixed [1239](https://github.com/weDevsOfficial/dokan/issues/1239)
> hide customer information from vendor order export based on setting

- templates/products/new-product-single.php
- templates/products/new-product.php
- templates/products/tmpl-add-product-popup.php
fixes: [1238](https://github.com/weDevsOfficial/dokan/issues/1238)
> Category name order by ascending

- includes/Walkers/TaxonomyDropdown.php
- templates/products/new-product.php
Here is a video demonstrating how to recreate this issue.
https://youtu.be/IlI4mF3NcFE
> Fix: After submitting the Create Product from the selected category is not selected

- assets/src/js/product-editor.js
- assets/src/js/script.js
- assets/src/js/store-lists.js
- includes/Vendor/UserSwitch.php
Related PR https://github.com/weDevsOfficial/dokan-pro/pull/1419
> fix: jQuery shorthand deprecation error fix

- includes/Rewrites.php
Now stores listing can make orderby random, just use `[dokan-stores orderby="random"]`
here ordering change randomly after every 10 minutes
> new: Stores listing orderby random

- templates/account/vendor-registration.php
> fix: Fatal error when vendor registration shortcode use on api

- templates/admin-setup-wizard/step-store.php
Fixed [1233](https://github.com/weDevsOfficial/dokan-pro/issues/1233)
> Map API selection on setup wizardadmin

- src/admin/pages/Withdraw.vue
Fixed [1251](https://github.com/weDevsOfficial/dokan/issues/1251)
> Vendor filter added on Withdraw page

- includes/REST/WithdrawController.php
- [fix] Added REST API Request for Withdrawal Create. Fixed #1198
> Added REST API request for Withdraw Create Request - Fixed #1198

- includes/Upgrade/Upgrades.php
- includes/Upgrade/Upgrades/BackgroundProcesses/V_2_9_23_StoreName.php
- includes/Upgrade/Upgrades/V_3_2_11.php
- includes/Upgrade/Upgrades/V_3_2_12.php
- includes/Vendor/Manager.php
Fixed https://github.com/weDevsOfficial/dokan/issues/1309
> fixed: dokan_store_name meta missing

- includes/Widgets/StoreLocation.php
Fixed https://github.com/weDevsOfficial/dokan/issues/1307
> fixed: Single store page map hide based on setting

- includes/Install/Installer.php
- includes/REST/WithdrawController.php
- includes/Upgrade/Upgrades.php
- includes/Upgrade/Upgrades/V_3_2_12.php
- includes/Withdraw/Manager.php
- includes/Withdraw/Withdraw.php
- src/admin/pages/Withdraw.vue
Related issue have on dokan pro https://github.com/weDevsOfficial/dokan-pro/issues/928
> new: Withdraw details keep save as log

- templates/store-lists.php
Found bug when activating ElasticPress, and tried to index.
> Fix: Check if pagination_base post is empty

- includes/Assets.php
- templates/products/listing-filter.php
- templates/products/new-product-single.php
- templates/products/products-listing.php
> fix: fixed warning on product listing page due to filter data type mismatch

- assets/src/js/store-lists.js
The user location auto detection feature has been removed as this feature causing other issue. 
fix https://github.com/weDevsOfficial/dokan-pro/pull/1549
> fix: remove user geolocation auto detection

- package.json
- src/utils/Bootstrap.js
Dokan Pro PR: https://github.com/weDevsOfficial/dokan-pro/pull/1397
> DateRangePicker library added

- includes/CacheInvalidate.php
- includes/Order/functions.php
- includes/Product/ProductCache.php
- includes/Vendor/VendorCache.php
- includes/functions.php
[fix] Fixed vendor related caches.
> Fixes and Improved some more caching issues

- includes/REST/Manager.php
- includes/REST/VendorDashboardController.php
endpoints: 
```
https://example.com/wp-json/dokan/v1/vendor-dashboard/
https://example.com/wp-json/dokan/v1/vendor-dashboard/sales?from=2021-08-02T04:13:05Z&to=2021-12-02T04:13:05Z
https://example.com/wp-json/dokan/v1/vendor-dashboard/orders
https://example.com/wp-json/dokan/v1/vendor-dashboard/products
https://example.com/wp-json/dokan/v1/vendor-dashboard/profile
```
> enhance: Dashboard API

- src/admin/pages/Vendors.vue
- src/admin/pages/Withdraw.vue
fix dokan pro issue  https://github.com/weDevsOfficial/dokan-pro/issues/1620
Has dokan pro PR https://github.com/weDevsOfficial/dokan-pro/pull/1621
> Fix Problem with Loading data when permalink sets to plain.

- includes/Vendor/VendorCache.php
- fix: Fixed New User create issue on lower version of WordPress < 5.8
- fix: Fixed some more cache deleting on delete and update user.
> fix: Fixed WP-User related caches for lower WP versions

- includes/ThemeSupport/Storefront.php
Previously, there was broken calendar layouts issue with the date range picker.
Now, fixed the above issue.
> fix: date range picker broken layout issue on storefront theme

- includes/Commission.php
> Item meta is not being deleted

- includes/Order/Hooks.php
> Showing Vendor or Store Name on the order details page of WooCommerce

- includes/Assets.php
Previously, there was no localization support to button labels of date range picker jQuery library.
Now, added localization support to the above library button labels.
Dokan Pro dependency: https://github.com/weDevsOfficial/dokan-pro/pull/1629
> enhance: localization support to date range picker button labels

- assets/src/js/helper.js
Added `dokan_get_date_range_picker_date_format()` function to the `helper.js` file for turning a date into `Date Range Picker` jQuery library supported date format.
> new: added dokan_get_date_range_picker_date_format() function to the helper.js file

- includes/Admin/Settings.php
- includes/Ajax.php
- includes/functions.php
Added `dokan_handle_recaptcha_validation()` function to the `functions.php` file for handling `Google reCaptcha` validation request.
pro dependency: https://github.com/weDevsOfficial/dokan-pro/pull/1673
> new: added dokan_handle_recaptcha_validation() function to the global functions.php file

- includes/Upgrade/Upgrades.php
- includes/Upgrade/Upgrades/V_3_3_7.php
- includes/Withdraw/Manager.php
Issue: [Dokan-pro](https://github.com/weDevsOfficial/dokan-pro/issues/1700)
**Before,**
There was an error id Debug Log when paying by Dokan stripe connect on checkout.
[Screenshot](https://prnt.sc/26g6n1p)
**Now,**
The issue is fixed.
Fix: https://github.com/weDevsOfficial/dokan-pro/issues/1700
> Fix db error while pay by dokan stripe connect.

- templates/products/new-product-single.php
Support for https://github.com/weDevsOfficial/dokan-pro/pull/1663
> Update: Compatibility with latest release of Rank Math SEO

- readme.txt
> content and link update of readme.txt

- includes/Admin/SetupWizard.php
fix: Fixed dokan popup enqueuing issue while wc vendor setup wizard.
> fix: Fixed dokan popup enqueuing issue while wc vendor setup wizard.

- includes/Dashboard/Templates/Products.php
The problem caused is because wp_insert_post was not setting post_date_gmt and post_modified_gmt automatically.
fixes this [Dokan Pro issue](https://github.com/weDevsOfficial/dokan-pro/issues/1711)
> added post_date_gmt and post_modified_gmt manually as they were not set automatically

- readme.txt
Added newly released Modules and descriptions.
> New modules description.

- templates/settings/store-form.php
fixes #1548
fixes https://github.com/weDevsOfficial/dokan-pro/issues/1786
> fix: Store Product Per Page is unable to save the value. After refresh, the value disappears from the Vendor Dashboard

- includes/Product/Manager.php
fixes https://github.com/weDevsOfficial/dokan-pro/issues/1766
> fix: Variable product's stock is not updated by quick edit from vendor dashboard

- readme.txt
added Dokan mobile app and youtube video of influecer.
> Update readme text

- includes/Assets.php
Fixes [this](https://github.com/weDevsOfficial/dokan-pro/issues/1812) issue from Dokan Pro
> fixed popup error in request withdraw popup in vendor dashboard

- assets/src/less/mixins.less
Fixes [this](https://github.com/weDevsOfficial/dokan-pro/issues/1782) Dokan Pro issue
now dokan lite and pro both looks like this for pending review products:
> fixed inconsistent UI for product with status 'pending review' between dokan pro and lite version

- dokan.php
- includes/REST/Manager.php
- includes/REST/OrderControllerV2.php
- includes/REST/VendorDashboardController.php
- includes/reports.php
Closes # .
1. visit `/dokan/v2/orders/{order_id}/downloads`
2. visit `/dokan/v1/vendor-dashboard/sales`
> As a …
> update: sales overview chart data population and order download endpoint

- includes/Vendor/Manager.php
- includes/Vendor/StoreListsFilter.php
- src/admin/pages/Vendors.vue
Issue:
Vendor Front-end > Store List > Order by - Recent > Shows inconsistent list of Vendors when compared to the List in Admin Dokan > Vendors List.
Changes Made:
With the changes made to the files, the inconsistency is resolved and the Order By-Recent shows correct listing of Vendors.
1. Check Admin > Vendor List Order
2. Check Vendor Front-end > Shop List > Order by - Recent
3. Inconsistency exists in the ordering of Vendors in the list
> Fix/StoreList > Orberby inconsistency

- includes/Admin/SetupWizard.php
Enqueued `dokan-fontawesome` style on Dokan vendor setup page
Closes # .
1. In vendor setup wizard, go to payment section
2. see if the 'info icon' is visible at the bottom section of bank payment method
> part of already merged PR …
> enqueue dokan-fontawesome style on vendor setup page

- readme.txt
> added stripe express on org content

- includes/Admin/Settings.php
- src/admin/components/Fields.vue
> fix: admin-settings-content-related-problem

- readme.txt
> updated success stories

- assets/src/less/dashboard.less
- includes/Vendor/SetupWizard.php
- includes/Withdraw/functions.php
part of [this](https://github.com/weDevsOfficial/dokan-pro/pull/1942)
> fix hide disconnect button on seller setup

- includes/Assets.php
- includes/Dashboard/Templates/MultiStepCategories.php
Fixes: New product add category ui.
1. Disable product popup and try to add new product. …
> New product add category ui fix

- src/admin/components/KnowledgeBase.vue
changelog page and import dummy data page are excluded from display.
> update: changelog and dummy data page excluded in knowledgebase

- src/admin/components/KnowledgeBase.vue
Reverts weDevsOfficial/dokan#1644
> Revert "update: changelog and dummy data page excluded in knowledgebase"

- includes/Admin/Settings.php
`dokan_settings_selling_options` filter used in dokan pro for Catalog Product
Related Dokan Pro PR: https://github.com/weDevsOfficial/dokan-pro/pull/1630
> added: dokan_settings_selling_options filter for catalog product

- includes/template-tags.php
Closes Issue-1 of this [dokan pro issue](https://github.com/weDevsOfficial/dokan-pro/issues/1914)
1. Please follow the steps in the issues
> **fix:** Vendor Dashboard left menubar not update 
> fix left menu not shown

- includes/Order/Manager.php
- templates/dashboard/products-widget.php
Closes https://github.com/weDevsOfficial/dokan/issues/1657 .
Closes https://github.com/weDevsOfficial/dokan-pro/issues/1965
1.
2.
3.
- **fix:** Fixed Order By sorting parameter for Orders …
> fix: fixed order default order by parameter

- src/admin/pages/Settings.vue
Closes https://github.com/weDevsOfficial/dokan/issues/1652
- **fix:** Changing withdraw method doesn't always show Withdraw Method Changed Modal window
> As a contributor, your responsibility is to learn from suggestions …
> fix: Changing withdraw method doesn't always show Withdraw Method Changed Modal window

- includes/Product/functions.php
- includes/Rewrites.php
Closes https://github.com/weDevsOfficial/dokan/issues/1649 .
- **fix:** Single store page default order by filtering wasn't working
> As a contributor, your responsibility is to learn from suggestions and iterate your …
> fix: Single store page default order by filtering wasn't working

- src/admin/pages/Dashboard.vue
> update: Changed Dokan Newsletter Subscription form to weMail

- assets/src/js/product-category-ui.js
- includes/Product/Hooks.php
- includes/ProductCategory/Helper.php
- templates/products/dokan-category-header-ui.php
- templates/products/new-product-single.php
- templates/products/new-product.php
- templates/products/tmpl-add-product-popup.php
Closes  https://github.com/weDevsOfficial/dokan-pro/issues/1954
**Dokan Pro PR:** https://github.com/weDevsOfficial/dokan-pro/pull/1962
1. Update product category ( Quick edit and bulk edit ) from vendor dashboard, multistep category UI is implemented there make sure UI works properly
2. Update product category from the admin dashboard, make sure all parent categories are selected after updating the product 
- **Enhance:** Implement new category UI in product Quick edit and bulk edit in vendor dashboard.
- **Fix:** When the admin updates or saves a product from the admin panel choose automatically all categories parents.
* KISS: Keep it simple, Sweetie …
> quick edit, bulk edit and admin product category update fix

- assets/src/js/product-category-ui.js
- includes/ProductCategory/Helper.php
Closes # .
1. Test bulk edit without changing category and after changing category. also, test on single category settings
2. Test quick edit without changing category and after changing category. also, test on single category settings
3. Test and add a new category box properly.
- **Fix:** Bulk edit and quick edit save error without selecting a category.
- **Fix:** Add new category box duplication. …
> bulk edit quick edit category fix

- dokan.php
- includes/CatalogMode/Admin/Settings.php
- includes/CatalogMode/Controller.php
- includes/CatalogMode/Dashboard/ProductBulkEdit.php
- includes/CatalogMode/Dashboard/Products.php
- includes/CatalogMode/Dashboard/Settings.php
- includes/CatalogMode/Helper.php
- includes/CatalogMode/Hooks.php
- templates/products/catalog-mode-content.php
1. Added two new admin settings for catalog mode
2. Added Vendor Settings to enable catalog mode
3. Added Product bulk edit support for catalog mode
4. Catalog mode can be controlled per product
Related Dokan Pro PR: https://github.com/weDevsOfficial/dokan-pro/pull/1959
Closes # .
1.
2.
3. …
> new: Added Catalog Mode Feature

- includes/Install/Installer.php
- includes/Upgrade/Upgrades.php
- includes/Upgrade/Upgrades/V_2_7_6.php
- includes/Upgrade/Upgrades/V_3_6_4.php
> fix: Removed unfiltered_html capabilities from vendors

- includes/Assets.php
- includes/Dashboard/Templates/MultiStepCategories.php
- templates/products/dokan-category-header-ui.php
Closes https://github.com/weDevsOfficial/dokan-pro/issues/1948
Dokan  Pro PR: https://github.com/weDevsOfficial/dokan-pro/pull/1981
1. Create and edit booking products from the vendor dashboard.
2. Create and edit auction products from the vendor dashboard.
- **Enhance:** Single & Multiple Category Select UI update for BOOKING and AUCTION …
> New dokan category integration in booking and auction product

- includes/ProductCategory/Helper.php
Closes #1682
1. Please follow this [video](https://www.loom.com/share/62377e6c94ca48dc827a2e5c309162e1), this will guide you how to test.
> Fix multiple sub-category unassigns by dokan if in the same parent
> As a …
> Fix multiple sub-category unassigns by dokan if in the same parent

- assets/src/js/product-category-ui.js
Closes #1681
1. `wp.hooks.addAction( 'dokan_multistep_category_selected', 'dokan-multistep-category', function ( selected_cat ) {
console.log(selected_cat + " this is the category.");
} );` You can add this code in js file or open the console and peast the code there it will work.
> Add dokan_selected_multistep_category hook in product-category-ui.js
> As a …
> Add dokan_selected_multistep_category hook in product-category-ui.js

- includes/Assets.php
- includes/Dashboard/Templates/MultiStepCategories.php
- includes/ProductCategory/Helper.php
Enqueue the scripts and styles of magnifying jquery CSS and dokan multistep category scripts and CSS. Also changes some code for enqueuing dokan multistep category.
**Dokan Pro PR:** [https://github.com/weDevsOfficial/dokan-pro/pull/2004](https://github.com/weDevsOfficial/dokan-pro/pull/2004)
Closes https://github.com/weDevsOfficial/dokan-pro/issues/2000
1. Enable SPMV, go to https://your-domain.test/dashboard/products-search/, Click, Create New then the create product popup is broken it is fixed now.
2. For more details or how to reproduce the guide you can see the [issue](https://github.com/weDevsOfficial/dokan-pro/issues/2000) description.
> Fix magnify popup style broken and dependency missing in SPMV search result page.
* Bad naming: make …
> Fix magnify popup style broken in SPMV search result page

- includes/Commission.php
- includes/ProductCategory/Helper.php
Closes https://github.com/weDevsOfficial/dokan-pro/issues/2006
1. Test category commission if it works properly and **commission will be applied to the last most young child category**
2. In the vendor subscription you can restrict any category now but before you could select only that parent who doesn't have any parent. Make sure in the vendor dashboard the selected category's ancestors and children are also allowed.
Update vendor subscription - allow all ancestors and children except siblings of the selected category
* Code that is not readable: too many nested 'if's are a …
> Fix and update category commission for multistep category

- includes/ProductCategory/Categories.php
Fix subscription product category restriction bug.
Closes # .
Dokan Pro PR: [https://github.com/weDevsOfficial/dokan-pro/pull/2029](https://github.com/weDevsOfficial/dokan-pro/pull/2029)
1. Before child's child was not showing but it is fixed now.
Fix subscription product category restriction bug.
> As a reviewer, your feedback should be focused on the idea, not …
> Fix subscription product category restriction bug.

- assets/src/js/script.js
- includes/Dashboard/Templates/Settings.php
- includes/Withdraw/functions.php
- templates/settings/bank-payment-method-settings.php
> Fix payment disconnect

- assets/src/less/products.less
Product and Variable product's variation image uploading height size overlaps.
Closes https://github.com/weDevsOfficial/dokan-pro/issues/2017
1. Choose a very long height image in the product image and the variable product image will overlap. now it is fixed.
Product and Variable product's variation image uploading height size overlaps. …
> Fix Product and variation product upload image overlap.

- includes/functions.php
- templates/products/listing-filter.php
- templates/products/products-listing.php
The product search of the product listing page of vendor dashboard is not working.
Closes #1713 
1. Try to search product by typing name in product list page in vendor dashboard.
Fix product search of the product listing page.
> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive …
> Fix product search of the product listing page.

- includes/functions.php
Stop multiple sub-order email notification when order status changed from failed to processing
Closes #1711
1. Make an order from multiple vendor. Then set status from the admin panel as failed  after saving change the order status to processing customer will get emails for both sub-orders. But customer should get email only for parent order.
Fix multiple emails are sent to the customer when a parent order's status is changed from failed to processing.
* Complicated constructions that need …
> Fix multiple emails are sent to the customer when a parent order's status is changed failed to processing

- templates/products/new-product.php
Fix product price, make default empty insted zero.
Closes #1725, Closes  #1720
1. Create a product disabling product popup, without any discount price.
Fix product price, make default empty insted zero
> As a …
> Fix product price, make default empty insted zero

- templates/orders/order-item-html.php
In the vendor dashboard, the single order details page in order item quantity and order total was not showing, There was some old code for dokan metadata that I removed. now it is working.
Closes #1724
1. Only in dokan-lite view an order details and quantity and total data is missing there.
Remove dokan meta data in order item in vendor dashboard
> As a reviewer, …
> Remove dokan meta data in order item in vendor dashboard

- includes/Admin/Settings.php
- includes/Assets.php
Fix decimal separator in dokan percentage commission.
Closes https://github.com/weDevsOfficial/dokan-pro/issues/1921
1. Set decimal separator in woocommerce settings and check if it works properly in dokan commission settings.
Fix decimal separator in dokan percentage commission.
> As a reviewer, your feedback should be focused on the idea, not the person. Seek to …
> Fix decimal saperator in dokan percentage commission.

- assets/src/js/product-editor.js
- templates/products/inventory.php
Closes https://github.com/weDevsOfficial/dokan-pro/issues/2020
Dokan pro Pr: https://github.com/weDevsOfficial/dokan-pro/pull/2026
1. Variable product variations stock setting should be the same as admin dashboard settings.
2. Low stock threshold is missing in variable variations. 
🐛 Fix variable product stock fields inconsistency and missing inputs fields.
> As a …
> Fix variable product stock fields inconsistency and missing inputs fields.

- assets/src/js/orders.js
The tax amount box takes multiple decimal places in the refund
Closes https://github.com/weDevsOfficial/dokan-pro/issues/1895
Dokan Pro PR: https://github.com/weDevsOfficial/dokan-pro/pull/2051
1. Now dokan refund tax take **more than 2** decimal digits but there is a setting in Woocommerce settings -> tax -> `Round tax at subtotal level, instead of rounding per line` checkbox. if it is not on a decimal point will be as woo-commerce settings `Number of decimals`. 
2. For more sure you can if dokan works exactly the same as woocommerce admin in a refund.
The tax amount box takes multiple decimal places in the refund
* KISS: Keep it simple, Sweetie (not …
> Tax amount box takes multiple decimal places in refund

- assets/src/js/dokan-admin-product.js
- assets/src/less/dokan-admin-product.less
- includes/Admin/Hooks.php
- includes/Assets.php
- webpack.config.js
When a shop manager publishes a product drafted by admin that product author changed to that shop manager. now it is fixed.
Closes #1719
1. Create a product from admin and make it drafted. then publish that product by the shop manager. That product will be assigned to that shop manager, which means that the product author changes to shop manager which is unexpected.
2. This scenario also happens if the vendor is in-active and the admin or shop manager changes the product data.
Fix produt assigned to wrong user if save by shop manager
* Code that is not readable: too many …
> Fix produt assigned to wrong user if save by shop manager

- templates/store-toc.php
Spaces between paragraphs are too large in store terms and condition page.
Closes https://lounge.wedevs.com/wp-admin/admin.php?page=pm_projects#/projects/39/task-lists/tasks/62777
Dokan Pro PR: https://github.com/weDevsOfficial/dokan-pro/pull/2074
1. Log in as a vendor. Navigate to store terms and conditions settings to set the t&C.
2. Type something and hit the “Enter” button after the ending of the sentence.
3. Start typing another para/sentence. Write three or more sentences like this.
4. The space between those paragraphs is too large than it should be.
5. Do the same in the vendor biography, but the spaces are alright in there.
Spaces between paragraphs are too large in store terms and condition page.
* Bad naming: make sure you would …
> Fix tnc allignment fix

- Gruntfile.js
- assets/src/js/dokan-admin-product.js
Closes # .
1.
Add dokan-admin-product.less to grunt.js for compilation
> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to …
> Add dokan-admin-product.less to grunt.js for compilation

- assets/src/js/dokan-admin-product.js
- includes/Admin/Hooks.php
Fix vendor assigning in quick and bulk edit in admin dashboard.
Closes # .
1.
2.
3.
Fix vendor assigning in quick and bulk edit in admin dashboard.
> As a contributor, your responsibility is to learn from suggestions and …
> Fix vendor assigning in quick and bulk edit

- includes/Admin/functions.php
> Fixed author was not updating for variations

- includes/Upgrade/Upgrades/V_3_6_4.php
Fix up grader not showing for ongoing upgrder error
Closes # .
Dokan Pro Pr: https://github.com/weDevsOfficial/dokan-pro/pull/2081
1.
2.
3.
Fix up grader not showing for ongoing upgrder error …
> Fix up grader not showing for ongoing upgrder error

- includes/Blocks/ProductBlock.php
- includes/Product/ProductAttribute.php
- includes/REST/ProductAttributeController.php
- includes/REST/ProductBlockController.php
- includes/REST/StoreSettingControllerV2.php
We've added some of Rest API support for Vendor dashboard.
- `dokan/v2/orders/`
- `dokan/v1/products/attributes/edit-product/{id}`
- `dokan/v1/blocks/products/{id}`
Related PR in PRO - https://github.com/weDevsOfficial/dokan-pro/pull/2075
> Fix dokan since

- src/admin/components/AdminNotice.vue
- src/admin/pages/AddVendor.vue
- src/admin/pages/DummyData.vue
- src/admin/pages/Settings.vue
Related Dokan Pro PR: https://github.com/weDevsOfficial/dokan-pro/pull/2086
Closes #1731
1.
2.
3.
- **fix:** SweetAlert library is conflicting with WooCommerce Conversion Tracking plugin …
> fix: SweetAlert library is conflicting with WooCommerce Conversion Tracking plugin

- includes/Product/Manager.php
- fix:  [BestSellingProductWidget] Products are being shown on the widget even when the catalog visibility is set to hidden. closes #1744
1.
2.
3.
> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and …
> fix: [BestSellingProductWidget] Products are being shown on the widget even when the catalog visibility is set to hidden

- includes/functions.php
- includes/template-tags.php
- templates/products/listing-filter.php
- templates/products/listing-status-filter.php
- fix: [VendorDashboardProducts] Products of different statuses are not displayed in the appropriate tab from the vendor dashboard. fixes #1740 
1.
2.
3. …
> fix: [VendorDashboardProducts] Products of different statuses are not displayed in the appropriate tab from the vendor dashboard.

- Gruntfile.js
- assets/js/dokan-frontend.js
- assets/src/js/dokan-admin-product.js
- assets/src/js/dokan-frontend.js
- assets/src/js/product-category-ui.js
- assets/src/js/script.js
- assets/src/less/general.less
- includes/Assets.php
- includes/Dashboard/Templates/Settings.php
- includes/Product/Hooks.php
- includes/ProductCategory/Helper.php
- includes/Widgets/FilterByAttributes.php
- includes/Widgets/ProductCategoryMenu.php
- includes/Widgets/StoreCategoryMenu.php
- includes/functions.php
- includes/template-tags.php
- templates/settings/store-form.php
1. fix: [ProductCategoryWidget] Sub Category dropdown on the Dokan Product Category widget doesn't work fixes #1739
2. fix: [AdminProduct] When editing a product in the WordPress backend, the vendor select dropdown doesn't contain any data. fixes #1750
3. fix: fixed a fatal error on the report page if the same day is selected for both the start and end date to generate reports
4. new: added a new hook named dokan_store_product_search_results to filter out store product search results closes https://github.com/weDevsOfficial/dokan/issues/1677
5.  Sort product categories under vendor dashboard alphabetically closes #1676 
6. fix: [VendorSoreSettings] Store settings update button wasn't working if the Dokan Pro plugin isn't activated.
1.
7.
8.
> Enter a summary of all changes on this Pull …
> Multiple Github Issues

- src/admin/pages/Vendors.vue
Closes https://github.com/weDevsOfficial/dokan-pro/issues/2083
Related to https://github.com/weDevsOfficial/dokan-pro/pull/2087
- **Fix:** Store filtering using category was not working …
> Fixed store category filtering

- includes/Withdraw/functions.php
- templates/settings/bank-payment-method-settings.php
Added a filter hook so that anyone can change the placeholders for their bank payment informations.
Closes # .
1. Use `dokan_bank_payment_fields_placeholders` Filter to change the label and placeholder of bank payment fields
Example:
```
/*
You can change any field title or remove any feild for the vendor -> settings -> payment -> bank transfer method. Please note that this
code need to be placed on your child-theme functions.php file
*/
/**
* Change the payment title
*
* @param array $methods
*
* @return array
*/
function dokan_2022_change_whithdraw_callback( $methods ) {
$methods ['bank']['title'] = __( 'Wire Transfer', 'dokan-lite' ); //title can be changed as per your need
return $methods;
}
add_filter( 'dokan_withdraw_methods', 'dokan_2022_change_whithdraw_callback', 12 );
/**
* …
```
> Add filter for bank payment fields placeholders

- includes/functions.php
Due to the integer type cast, the Total Sales were not showing the floated values. So, this PR has changed the type cast to fix the issue.
- Previous: https://snipboard.io/5Jac2d.jpg
- Current: https://snipboard.io/83sGMJ.jpg
Closes #.
1.
2.
3.
> As a reviewer, …
> [Fix]: Big counter widget total sales value type cast

- includes/template-tags.php
> Update/vendor dashboard UI

- includes/Dashboard/Templates/Orders.php
- includes/Order/Manager.php
- includes/REST/OrderController.php
- includes/REST/VendorDashboardController.php
> Update api order list filter

- includes/Dashboard/Templates/MultiStepCategories.php
* Changed category modal template adding method to `wp_footer` hook instead of `dokan_before_product_content_area`, `dokan_before_new_product_content_area`, and `dokan_before_new_product_content_area` hooks. Which was generating wrong placement issues of product category selection modal on some themes including `beTheme`.
* This PR is associated with `Dokan Pro` PR: https://github.com/weDevsOfficial/dokan-pro/pull/2147
Closes # https://lounge.wedevs.com/wp-admin/admin.php?page=pm_projects#/projects/39/task-lists/tasks/62809.
1. Swith theme to `beTheme`.
2. Goto vendor dashboard.
3. Open product adding or editing form.
4. Open the product category selection modal and its placement should be proper.
> fix: Wrong placement of product category selection modal on vendor dashboard
* Code is not …
> fix: Wrong placement of product category selection modal on vendor dashboard

- includes/Order/functions.php
`instanceof WC_Abstract_Order` checking removed from `dokan_get_seller_id_by_order` function.
Closes # .
1.
2.
3.
> refactor: dokan_get_seller_id_by_order function
> As a contributor, your responsibility is to learn from …
> refactor: dokan_get_seller_id_by_order function

- includes/Blocks/ProductBlock.php
- includes/Product/functions.php
- includes/REST/ProductBlockController.php
- includes/REST/ProductController.php
- includes/REST/ProductControllerV2.php
- includes/Vendor/SettingsApi/Settings/Pages/Store.php
> Update: product api

- includes/Admin/Hooks.php
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2158 .
1. Go to WC Product edit/ create screen
2. Search for vendor from vendor card.
**fix**: vendor search with store name from WC Product Edit screen
> As a reviewer, your feedback should be focused on …
> fix: vendor search with store name from WC Product Edit screen

- includes/Order/functions.php
- includes/wc-functions.php
Added order counts based on currently logged-in vendor on WP dashboard orders listing page.
* Closes #  https://github.com/weDevsOfficial/dokan/issues/1784.
1. Make sure that the `Admin Area Access` option is enabled for vendor on `Admin Dashboard` > `Dokan` > `Settings` > `General`.
2. Login into a vendor account and go to `Admin dashboard` > `WooCommerce` > `Orders`.
3. The order counts should be shown as per the vendor's store orders.
> enhance: WP dashboard order counts for vendor
* …
> enhance: WP dashboard order counts for vendor

- includes/Commission.php
Fixed critical error on creating order from the admin dashboard as per this issue: #1798 
* Closes: #1798 
1. Go to `Dokan` > `Settings` > `Selling Options`.
2. Set `Shipping Fee Recipient` to `Admin`.
3. Then go to `WooCommerce` > `Orders` > `Add Order`.
4. Create a new order using the `Create` button.
5. There should not be any fetal error as previously shown as per the linked issue.
> fix: Critical error on creating order from the admin dashboard
* Complicated constructions that need …
> fix: Critical error on creating order from the admin dashboard

- includes/Admin/Settings.php
Updated label and description of the `Enable Selling` option from the admin dashboard.
* Closes #1416.
1. Please go to `WP Admin Dashboard` > `Dokan` > `Settings` > `Selling Options`.
2. Under `Vendor Capabilities` the `New Vendor Product Upload` option changed to `Enable Selling`.
3. Also, updated the descript under the label.
> update: Enable selling option from the admin dashboard …
> update: Enable selling option from admin dashboard

- assets/src/js/product-category-ui.js
- includes/ProductCategory/Helper.php
Before in product add/edit page user had to select the most child category to add or edit product 
1. We have introduces a `javascript` filter hook named `dokan_middle_category_selection`, by using this hook if anyone passes `true` in this hook user will be able to select any category in dokan multi-step category.
2. We also introduced a hook for `php` end named same as `dokan_middle_category_selection` and you also have to pass `true` select middle category.
**Note: To get the final result we must implement the both hook or it woun't work properly.** 
Closes # .
1. in any js file use `dokan_middle_category_selection` filter hook pass `true` in it. user will be able to select any category.
2. JavaScript Hook example:
```
wp.hooks.addFilter('dokan_middle_category_selection', 'dokan', …
```
> 🪝 Enhance: Add hook to select any category

- assets/src/js/product-editor.js
* Closes #1806.
1. Check issue #1806
> As a contributor, your responsibility is to learn from suggestions and iterate …
> fix: featured image could not be added on product created with `Create and add new` button

- includes/Admin/Settings.php
* Closes: https://github.com/weDevsOfficial/dokan-pro/issues/2216 .
1. Go to WP **Dashboard > Dokan > Settings > Appearance > Store Appearance > Hide Vendor Info**.
2. There should be a sub-description shown under the **Hide Vendor Info** option.
> enhance: Add sub-description to the hide vendor info section in admin appearance settings …
> enhance: Add sub-description to the hide vendor info section in admin appearance settings

- assets/src/less/products.less
Closes #1758.
1.
2.
3.
- fix: Fixed product image thumbnail gets image height squeezed on add new product popup under vendor dashboard
> As a contributor, your responsibility is to learn from suggestions and iterate your …
> Fix product image thumbnail gets image height squeezed on add new product popup under vendor dashboard

- includes/Order/Manager.php
- includes/Withdraw/functions.php
- includes/functions.php
- includes/reports.php
- includes/wc-functions.php
- uninstall.php
> fix: sql injection on some queries.

- src/admin/pages/Settings.vue
* related PR https://github.com/weDevsOfficial/dokan-pro/pull/2227
1. Please check https://github.com/weDevsOfficial/dokan-pro/pull/2227
update: disbursement schedule change detection and announcement sending consent
> As a reviewer, your feedback should be focused …
> update: disbursement schedule change detection and announcement sending consent

- includes/REST/ProductControllerV2.php
Converted schema parameter value into an array to fix the WP Rest Server error when the Dokan Lite plugin was activated.
Closes #.
1.
2.
3. …
> Fix/WP Rest Server error when Dokan Lite plugin was activated

- assets/js/vendor-address.js
- includes/Assets.php
All countries state fields are not required but some are required and.
* Closes #1709
* Dokan Pro PR: https://github.com/weDevsOfficial/dokan-pro/pull/2235
1. Select Turkey and UK and Us and bangladesh the state title are not the same and all states are not required.
🛠 Fix: vendor state required …
> 🛠 Fix: vendor state requiired

- readme.txt
> March 9, 2023 Updated content

- includes/functions.php
Previously, the count of default store categories increased if another user is added other than the vendor role. Now, fixed the issue and added an upgrader to fix existing store category counts.
* This PR has a dependency on: https://github.com/weDevsOfficial/dokan-pro/pull/2253
* Closes # https://github.com/weDevsOfficial/dokan-pro/issues/2095.
* Please follow the steps from https://github.com/weDevsOfficial/dokan-pro/issues/2095.
> enhance: store category counts improvement.
* Complicated …
> enhance: Store category counts improvement

- assets/js/vendor-registration.js
- includes/Registration.php
Now, new vendor won't be able to signup if the store URL is not available.
* Closes: https://github.com/weDevsOfficial/dokan-pro/issues/2212.
1. Go to `My Account` page.
2. Try to signup as a vendor with an existing store URL.
3. It will be prevented by throwing an alert.
> fix: Vendor can signup even though store URL not available warning exists
> As a reviewer, …
> fix: Vendor can signup even though store URL not available warning exists

- includes/REST/ProductController.php
Closes #1829
1.
2.
3.
> fix: `in_stock`, `featured`, `on_sale` filter for products rest API wasn't working
> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be …
> [RestAPIProduct] `in_stock`, `featured`, `on_sale` filter for products rest api wasn't working

- includes/Withdraw/functions.php
Closes # .
1.
2.
3.
Fix: get withdraw payment method title
> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and …
> Fix: get withdraw payment method title

- includes/Vendor/Manager.php
Previously, when the selling is disabled from the vendor edit screen of the WordPress admin panel, the products are kept in `Published` status. Now, the product status updating on selling option changing from vendor edit admin dashboard.
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2263.
* Please follow the steps from https://github.com/weDevsOfficial/dokan-pro/issues/2263
> fix: Product status not updating on selling option changing from vendor edit admin dashboard
* …
> fix: Product status not updating on selling option changing from vendor edit admin dashboard

- includes/REST/VendorDashboardController.php
Fix some console errors .
* Closes https://github.com/weDevsOfficial/vendor-dashboard/issues/57
* Vendor dashboard PR: https://github.com/weDevsOfficial/vendor-dashboard/pull/54
1. Follow the issues and test them. as desribed there
Update vendor dashboard report api …
> 🛠️Fix: vendor dashboard report data error

- includes/functions.php
Previously, on the vendor dashboard product listing page was showing wrong product counts. Now, fix the product counts by this PR.
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2047.
* Please follow the steps from https://github.com/weDevsOfficial/dokan-pro/issues/2047.
> fix: Wrong product counts on vendor dashboard product listings
> As a reviewer, …
> 🪲 fix: Wrong product counts on vendor dashboard product listings

- readme.txt
> Updated contents and grammar fix

- readme.txt
Rows 192-214
Closes # .
1.
2.
3.
> As a contributor, your responsibility is to learn from suggestions and iterate your …
> Format update

- assets/src/js/product-editor.js
Previously, vendors can upload and select non-image format files as product cover and gallery images to the product add/edit page and popup. Now, only image format files made allowed to upload and use as product cover and gallery images.
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2283.
1. Go to vendor dashboard.
2. Go to product add/edit page and popup.
3. Try to upload and select product featured and gallery image.
4. Non-image file can't be uploaded or selected.
> enhance: Allow only image format files as product featured and gallery images on vendor dashboard
* DRY: Don't Repeat …
> 🚀 enhance: Allow only image format files as product featured and gallery images on vendor dashboard 

- includes/Vendor/SetupWizard.php
* Closes: https://github.com/weDevsOfficial/dokan-pro/issues/2108.
* Please follow the steps from https://github.com/weDevsOfficial/dokan-pro/issues/2108.
> enhance: Allow countries in location selectors based on admin allowed countries in WooCommerce settings. …
> 🚀 enhance: Allow countries in location selectors based on admin allowed countries in WooCommerce settings

- assets/src/js/product-editor.js
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2286.
* Follow the steps from https://github.com/weDevsOfficial/dokan-pro/issues/2286.
> fix: Console error on uploading non-image file to product gallery
> As …
> 🔩 fix: Console error on uploading non-image file to product gallery

- assets/src/less/orders.less
Vendor dashboard single order invoice and packaging button broken issue fix
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2254
1.
2.
3.
> fix: Order invoice and packaging slip broken css
> As a contributor, …
> fix: Order invoice and packaging slip broken css

- assets/js/vendor-registration.js
Previously, getting console error at register page for some themes including `Dokan Theme`. Also, customers are not being able to register for some themes. Now, fixed the issue by this PR.
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2287.
* Please follow the steps from https://github.com/weDevsOfficial/dokan-pro/issues/2287.
> fix: Customers are unable to register on some themes and console error on the My Account page
* Complicated constructions that need refactoring or …
> 🔨 fix: Customers are unable to register on some themes and console error on the My Account page

- assets/src/js/script.js
Extra element added by jQuery form validator plugin for error message propagation issue
Closes https://github.com/weDevsOfficial/dokan-pro/issues/2249
+ Closes https://github.com/weDevsOfficial/dokan-pro/issues/2249
1.
2.
3.
> Social profile link on vendor dashboard's design issue fixed.
> As a reviewer, your feedback should be focused on the idea, not the person. …
> fix: Extra space propagation issue on from validation

- src/admin/components/TextEditor.vue
- src/admin/pages/Settings.vue
Closes https://github.com/weDevsOfficial/dokan-pro/issues/2116
1. Try to search with long string.
2. Search editor setting from search box the editor should not break.
Fix tinymc editor and seach box overlap
> As a …
> Fix tinymc editor and seach box overlap

- includes/ThemeSupport/Astra.php
Astra theme support css relocated to dokan lite.
- Closes https://github.com/weDevsOfficial/dokan-pro/issues/2293
1.
2.
3.
> Astra css issue fix
> As a contributor, your responsibility is to learn from suggestions and …
> fix: Astra theme support css relocation

- src/admin/components/Fields.vue
Closes # .
1.
2.
3.
> fix: Vendor analytics admin settings Google sign-in button broken style)\
> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based …
> fix: Vendor analytics admin settings Google sign-in button broken style

- includes/ReverseWithdrawal/BackgroundProcess/CronActions.php
- includes/ReverseWithdrawal/Helper.php
- includes/ReverseWithdrawal/InstallerHelper.php
Fixed partially https://github.com/weDevsOfficial/dokan-pro/issues/2244
1.
2.
3.
> **update:**  [ReverseWithdrawal] Added sold individually param to true for advertisement base product when creating it, so that quantity can't be changed …
> ReverseWithdrawal: Added Sold Individually Parameter to true 

- assets/src/js/login-form-popup.js
- assets/src/js/withdraw.js
Closes https://github.com/weDevsOfficial/dokan-pro/issues/2103
> **update:** [ColorSchemeCustomizer] Used color set by Color Scheme Customizer Module instead of hardcoded value for login form popup and withdraw schedule popup header color …
> 🔧 chore(js): use dokan.modal_header_color variable instead of hardcoded color code in login-form-popup.js and withdraw.js files

- assets/src/js/product-editor.js
- includes/Ajax.php
- templates/products/edit-product-single.php
- templates/products/products-listing-row.php
- templates/products/products-listing.php
Removed expected earning calculation from product listing and editing pages.
Closes # .
1.
2.
3.
> enhance: Remove expected earning calculation from product listing and editing pages …
> 🚀 enhance: Remove expected earning calculation from product listing and editing pages

- templates/store-header.php
Single store page verification badge showing
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2327
1.
2.
3.
> Single store page verification badge
> As a contributor, your responsibility is to learn from …
> Single store page verification badge

- includes/Install/Installer.php
Closes https://github.com/weDevsOfficial/dokan-pro/issues/2123
> **update:** Added dokan_store_name meta-key for all users with administrator and shop_manager roles during plugin activation …
> 🚀 feat(Installer.php): add store name meta key for admin users

- templates/global/product-tab.php
Remove rating of vendor information tab when WooCommerce review is disabled
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2321
Related Dokan Pro PR: https://github.com/weDevsOfficial/dokan-pro/pull/2325
1.
2.
3.
> Review removed from vendor information tab when WooCommerce review is disabled.
> As a reviewer, your feedback should be focused on the …
> WooCommerce disable review

- includes/REST/Manager.php
- includes/Vendor/Vendor.php
Closes partially: https://github.com/weDevsOfficial/dokan-pro/issues/2260
> **update:** Added PHP version 8.1 compatibility for Dokan
> As a contributor, your responsibility is to learn from suggestions and iterate your …
> fix: php 8.1 notices

- includes/Widgets/ProductCategoryMenu.php
Fix the incorrectly closed product category menu because of reassigned arguments that let `after_widget` undefined and brokes the layout.
1. Implement the Product Category menu in the sidebar.
2. Inspect and test if the closing tag was added by the browser itself or not. (I am using Elementor with Besa theme and this was detected and solved with this PR changeset).
> Fix - Incorrectly closed product category menu `after_widget` args.
* Complicated constructions that need refactoring or …
> Fix - Incorrectly closed product category menu after_widget args

- includes/functions.php
* https://github.com/weDevsOfficial/dokan-pro/pull/2352
* Closes: https://github.com/weDevsOfficial/dokan-pro/issues/2350
* Closes: #1785 
* Check https://github.com/weDevsOfficial/dokan-pro/issues/2350
> Can check dashboard page inside product loop
> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and …
> Dokan vendor dashboard detection inside product loop

- includes/template-tags.php
Fix: store page pagination
* Closes #1805
1. Store page pagination next and preview line does not shows properly.
>Fix: dokan store page pagination doesn't work properly
> As a contributor, your responsibility is to …
> ✍️Fix: store page pagination

- assets/src/less/products.less
* Fixes: https://github.com/weDevsOfficial/dokan/issues/1871#issuecomment-1568805393.
1. Please go to `Admin Dashboard` > `Dokan` > `Settings` > `Selling Options`.
2. Enable `Disable Product Popup` under the `Vendor Capabilities` Section.
3. Go to `Vendor Dashboard` > `Products` > `Add New Product`.
4. The styling of the `Discounted Price` input section should be fine.
> fix: Styling issue of discounted price input section in vendor dashboard product adding page
>> In the vendor dashboard product-adding page, the styling issue with the discounted price section has been fixed. Previously, there was a problem with the layout for certain themes that had wider page layouts.
* Bad naming: make sure you would understand your code if you read it a …
> 🎨 fix: Styling issue of discounted price input section in vendor dashboard product adding page

- DEVELOPER.md
- bin/clean-useless-files.js
Add: developer guid for dokan lite
Closes # .
1.
> Added developer guide for dokan lite. It will help developer to install and build assets in dokan lite.
> As a contributor, your responsibility is to learn from …
> Add: developer guid for dokan lite

- assets/src/less/setup.less
- includes/Vendor/SetupWizard.php
Previously, there were no store location map selection fields on the store setup wizard. Now, the fields are added by this PR.
* Closes #1270.
1. Go to the seller setup wizard.
2. Store location map fields should be there.
> enhance: Store location map integration on the seller setup wizard
>> Introducing a new enhancement in the seller setup wizard: seamless integration of a store location map. This enhancement allows sellers to effortlessly navigate and locate their store's position within the wizard interface.
* Code that is not readable: too many nested 'if's are a bad …
> 🗺 enhance: Store location map integration on seller setup wizard

- includes/REST/WithdrawController.php
Fix: The withdraw request could not be approved from admin dashboard by api
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2452
1. Try to update withdraw request from admin dashboard and from postman including all information 
> Fix: The withdraw request could not be approved from admin dashboard by api
> As a reviewer, your feedback should be focused …
> Fix: The withdraw request could not be approved

- package.json
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2460
* Closes https://github.com/weDevsOfficial/dokan/issues/1940
* Check https://github.com/weDevsOfficial/dokan-pro/issues/2460
**Missing translation added**
Previously `template` folder at dokan-lite was missing when .pot file was generated before release. After this update `template` folder will be respected when pot file is generated …
> `template` folder added to translation .pot file generator at package.json script

- includes/Assets.php
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2407.
* Please follow the steps from: https://github.com/weDevsOfficial/dokan-pro/issues/2407.
> fix: Console warning from Google Map on backend and frontend
> …
> 📍 fix: Console warning from Google Map on backend and frontend

- assets/src/js/login-form-popup.js
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2497
* Check https://github.com/weDevsOfficial/dokan-pro/issues/2497
**Login popup from closes properly**
Previously when reporting an abuse of a product, the login form wasn't closing properly. After this update the login form will close properly.
> As a reviewer, your feedback should be focused on the …
> login form closing class name mismatch

- includes/ReverseWithdrawal/Helper.php
- includes/ReverseWithdrawal/Hooks.php
Closes partially https://github.com/weDevsOfficial/dokan-pro/issues/2621 .
1. Admin account needs to fall under Reverse withdrawal rule
2. Vendor tries to pay for reverse balance, add to cart fails
1. Admin tries to pay for his own reverse withdrawal 
2. Add to cart fails due to the rules `vendor can't purchase his own product`
* Complicated constructions that need refactoring or comments: …
> [ReverseWithdrawal] Vendor/Admin cannot pay for reverse withdrawal balance

- readme.txt
> Updated readme.txt 

- includes/Withdraw/functions.php
Fix: Keep the backward compatibility for dokan_withdraw_method_additional_info filter hook
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2478
* Pro PR: https://github.com/weDevsOfficial/dokan-pro/pull/2479
1. Checkout dokan lite branch to v3.7.20 and pro to the latest
2. Setup up a custom withdraw method in dokan settings
3. Go to withdraw menu in vendor dashboard page fatal error is there.
> Fix: Keep the backward compatibility for dokan_withdraw_method_additional_info filter hook
* Performance …
> Fix: Keep the backward compatibility for dokan_withdraw_method_additional_info filter hook

- includes/Emails/VendorWithdrawRequest.php
* Closes #1949.
* Please follow the steps from #1949.
> fix: Amount field of new withdraw submission email template not working
> As a contributor, your responsibility is to learn from suggestions and iterate your pull …
> 📧 fix: Amount field of new withdraw submission email template not working

- assets/src/less/dashboard.less
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2489
1. Please follow the steps from: https://github.com/weDevsOfficial/dokan-pro/issues/2489.
2. Also, please check other date-range selector calendars all over the vendor dashboard.
> fix: Date-range selection calendar of vendor dashboard broken on multiple themes …
> 📅 fix: Date-range selection calendar of vendor dashboard broken on multiple themes

- includes/Product/Hooks.php
Fix Invalid filter on lite and booking module hide product type filter on product page
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2469
* Dokan pro PR: https://github.com/weDevsOfficial/dokan-pro/pull/2598
1.
2.
3.
> When only dokan lite is activated then we don't need to show the product type  filter because we support only one product type in dokan lite. And when woo-commerce booking integration is enabled in dokan then we won't show product type filter but in products page. but before in products page it was removed when booking module is enabled. Now if enable booking product the filter will be workable in products page.
* KISS: …
> Fix: Invalid filter on lite and booking module

- assets/src/less/site-navigation.less
Fix mobile menu background color in responsive view.
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2499
1. Check mobile menu background color before it was balck now it should be as color scheme
> Fix mobile menu background color in responsive view. …
> Fix: mobile menu background color

- assets/src/js/dokan-admin-product.js
- includes/Admin/Hooks.php
Hide vendor select section when select subscription product and assign admin or current user as author for new subscription product and update.
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2487
1. Try to add subscription product and the vendor section should be hidden for existing product the author will be the owner of the product even if select simple product and change author then if select subscription product the author will be admin for new product and previous author for edit product.
> When create subscription product and the vendor section should be hidden for existing product the author will be the owner of the product even if select simple product and change author then select subscription product the author will be admin for new product and previous author for …
> Enhancement hide vendor select box on subscription product

- includes/DummyData/Importer.php
When clear all dummy data all products are being deleted and when trying to delete booking product that has order by a customer and error was producing. Now this fix will delete only the dummy product and will not touch non dummy products.
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2157
1.
2.
3.
> When clear all dummy data all products are being deleted and when trying to delete booking product that has order by a customer and error was producing. Now this fix will delete only the dummy product and will not touch non dummy products.
* Code that is not …
> Fix: Trying to delete all products also booking product and also trying to delete non-dummy product

- tests/Withdrawal/MakeDefaultWithdrawalMethodTest.php
> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater …
> test: Default withdrawal method ajax test

- includes/REST/DummyDataController.php
- src/admin/pages/DummyData.vue
Fix: Dokan dummy data 502 unexpected error message while importing
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2431
1. Test this issue as mentioned in the issue description.
>  Handle dokan dummy data 502 unexpected error message while importing data.
> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, …
> Fix: Dummy data 502 unexpected error.

- assets/src/js/orders.js
Before in refund the tax amount decimal point rounding precision was not same as woocommerce, now it has consistancy with woocommerce.
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2408
1. Try to refund and check the tax amount.
> Before in refund the tax amount decimal point rounding precision was not same as woocommerce, now it has consistancy with woocommerce.
* …
> Fix: order refund amount tax decimal precision

- includes/Order/Hooks.php
* Closes https://github.com/weDevsOfficial/dokan-pro/issues/2651
* Check: https://github.com/weDevsOfficial/dokan-pro/issues/2651
* Has dependency on Dokan Pro PR: https://github.com/getdokan/dokan-pro/pull/2674
Previously dokan-lite plugin was not respecting dokan plugin's coupon configuration. After this update dokan-lite will fully support dokan's coupon configuration including some corner cases. …
> Dokan compatibility added.

- includes/Order/functions.php
* Closes #2001.
1. Please go to the vendor dashboard and turn an order status into `Draft`.
2. Check the order listing page and order details page.
3. The order status should have existed, which was previously missing if the status was `Draft`.
> fix: Order status label missing on vendor dashboard for draft orders
> As a reviewer, your feedback should be focused on …
> 🎯 fix: Order status label missing on vendor dashboard for draft orders

- templates/orders/details.php
* Closes https://github.com/getdokan/dokan-pro/issues/2703.
* Please follow the steps from https://github.com/getdokan/dokan-pro/issues/2703.
> fix: Shipment button and form still available on vendor dashboard single order page if shipment creation enabled from admin settings
> As a reviewer, your feedback should be focused on the idea, not the person. Seek to …
> 🎯 fix: Shipment button and form still available on vendor dashboard single order page if shipment creation enabled

- .github/pull_request_template.md
* Related PR section and checkbox added
* Closes section format updated
* Issue testing section format updated
* Changelog entry format and instructions updated
Closes # .
1.
2.
3.
pull_request_template.md updated as per our current practice.
> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus …
> Pull request template updated.

- includes/Product/Hooks.php
- includes/ProductSections/Manager.php
* Full PR Link
* Closes #
*enhance: Positioning of additional product sections and product filtering*
* Bad naming: make sure you will your code if you read it a few months from now.
* …
> 🚀 enhance: Positioning of additional product sections and product filtering

- assets/src/less/responsive.less
- templates/products/products-listing.php
* Full PR Link
* Closes #2004.
* Closes #2014.
* Please follow the steps from #2004 & #2014.
*fix: Mobile responsive issues of vendor dashboard products listing page* …
> 📱 fix: Mobile responsive issues of vendor dashboard products listing page

- assets/src/less/withdraw.less
Fix: withdraw page mobile responsive
* Full PR Link
* Closes #2002
* Test the responsive ui of withdraw pages
> Fix: withdraw page mobile responsive
Withdraw page was not mobile responsive
Now it is responsive …
> Fix: withdraw page mobile responsive

- includes/REST/OrderController.php
* Full PR Link
* Closes https://github.com/getdokan/dokan-pro/issues/2821
*Title*
* Grammar …
> 🐛 fix(OrderController.php): add get_item method to retrieve order details by ID

- assets/src/js/product-editor.js
* https://github.com/getdokan/dokan-pro/issues/2731
* https://github.com/getdokan/dokan-pro/issues/2731
*Special Case of Select All*
Previously Select All than Select None and again Select All didn't work. This is under vendor product edit page for simple product. This is a special case for Select All under Attributes section. After this update all the special case of select all will work perfectly.
Previously, Select All, Select None and Select All sequence didn't work.
After this PR the above mentioned sequence will work perfectly.
* DRY: Don't Repeat …
> Select All attribute not working issue fix.

- src/admin/components/PasswordGenerator.vue
* Full PR Link
* Closes https://github.com/getdokan/dokan/issues/2069
* Check issue https://github.com/getdokan/dokan/issues/2069
Not needed
> As a reviewer, your feedback should be focused on the idea, not …
> fix: Regenerate button typo

- assets/src/js/product-editor.js
* Full PR Link
* Closes https://github.com/getdokan/dokan-pro/issues/2756
* Steps or issue link https://github.com/getdokan/dokan-pro/issues/2756
update: Remove minimum input length restriction on Product page Tag field
* …
> update: Remove minimum input length restriction on Tag field

- includes/Vendor/Vendor.php
- tests/Vendor/UserToVendorTest.php
* Full PR Link
* Closes https://github.com/getdokan/dokan/issues/2077
* Check issue https://github.com/getdokan/dokan/issues/2077
No change log is needed.
* Complicated constructions that need refactoring or comments: code …
> fix: Vendor class `shop_data` persistence is broken on `save()`

- includes/REST/OrderController.php
* Full PR Link
* Closes https://github.com/getdokan/dokan-pro/issues/2914
*Title*
* Grammar …
> Fix, returns empty orders list in dokan rest api.

- includes/Vendor/SetupWizard.php
* Full PR Link
* Closes https://github.com/getdokan/dokan-pro/issues/2859
fix: Issue in displaying vendor map address on store listing page after setup wizard configuration
> As a …
> fix: Issue in displaying vendor map address on store listing page after setup wizard configuration

- includes/Dashboard/Templates/Dashboard.php
- includes/functions.php
- templates/dashboard/orders-widget.php
- templates/dashboard/products-widget.php
* Full PR Link
* Closes https://github.com/getdokan/dokan/issues/2079
* Check issue https://github.com/getdokan/dokan/issues/2079
fix: Several functionalities on the Vendor Dashboard, such as live product updates for pending orders, are not functioning correctly
* Complicated constructions that need refactoring or comments: code …
> fix: Several functionalities on the Vendor Dashboard, such as live product updates for pending orders, are not functioning correctly

- includes/Frontend/MyAccount/BecomeAVendor.php
* Full PR Link
* Closes https://github.com/getdokan/dokan/issues/2100
fix: The indication of whether the store is available or not is absent on the vendor migration form
> As a …
> fix: The indication of whether the store is available or not is absent on the vendor migration form

- includes/Shipping/Hooks.php
* Full PR Link
* Closes https://github.com/getdokan/dokan/issues/2068
* Check issue https://github.com/getdokan/dokan/issues/2068
fix: When a customer buys digital and physical products from different vendors, shipping charges are applied separately to each vendor
* Code that is not readable: too many nested 'if's …
> fix: When a customer buys digital and physical products from different vendors, shipping charges are applied separately to each vendor

- includes/template-tags.php
* https://github.com/getdokan/dokan-wpml/pull/33
* Closes https://github.com/getdokan/client-issue/issues/64
* Check Issue https://github.com/getdokan/client-issue/issues/64
fix: Translation-Related Issues with Specific Menu Items in Vendor Dashboard with WPML
* Complicated constructions that need refactoring or comments: code should …
> fix: Translation-Related Issues with Specific Menu Items in Vendor Dashboard with WPML

- assets/src/js/dokan-daterangepicker.js
- assets/src/js/helper.js
- includes/Assets.php
* Full PR Link
* Closes (partial) https://github.com/getdokan/client-issue/issues/65 
* Check issue number 2 and 3 and 4 at https://github.com/getdokan/client-issue/issues/65 
fix: Translation-related issues with date range picker
fix: Translation-related issues with Dokan Sweetalert
* Complicated constructions that need refactoring …
> fix: Translation-Related Issues with daterange picker and SweetAlert

- includes/Dashboard/Templates/Withdraw.php
Add check for withdrawal class to get withdraw data.
- If you have enabled cache then create a withdraw and check any fatal error occurs.
```
Fix: add a withdraw class check in Templates/Withdraw.php class to avoid error.
```
* …
> Add check for withdrawal class to get withdraw.

- includes/Admin/functions.php
- includes/Emails/VendorCompletedOrder.php
- includes/Emails/VendorNewOrder.php
- includes/Vendor/SetupWizard.php
- templates/store-lists-filter.php
* https://github.com/getdokan/dokan-pro/pull/3053
* Closes (partial) https://github.com/getdokan/dokan-pro/issues/2879
No change log needed …
> fix: PHP 8.2 Compatibility Issues

- includes/Order/Admin/Hooks.php
Fixed when HPOS is enabled, sub-orders disappear when orders are filtered by a specific vendor in admin dashboard
* Closes #2147
* Watch the video provided in the issue.
```
Fix: sub-orders disappear when orders are filtered by a specific vendor in admin dashboard when HPOS is enabled.
```
> As a reviewer, your feedback should be focused on the idea, not the …
> Fix: When HPOS is enabled, sub-orders disappear when orders are filtered by a specific vendor

- src/admin/pages/Vendors.vue
Show html entity as real HTML
* Dokan Pro PR: https://github.com/getdokan/dokan-pro/pull/3063
* Closes https://github.com/getdokan/dokan-pro/issues/3021
* The reproduce steps mentioned in the issue beautifully
```
Fix: HTML entity appearing on the store category
``` …
> Fix: HTML entity appearing on the store category

- includes/functions.php
* Full PR Link
* Closes https://github.com/getdokan/dokan-pro/issues/3071
*Title*
* Grammar …
> fix: Many strings in Dokan shipping settings and related screens cannot be translated using WPML

- includes/Product/ProductCache.php
* Full PR Link
* Closes https://github.com/getdokan/dokan/issues/2163
No changelog needed
> As a reviewer, your feedback should be focused on the idea, not the person. Seek to …
> update: `dokan_product_cache_delete_all_data` filter added in `ProductCache::delete()`

- assets/src/less/store-lists.less
* Full PR Link
* Closes https://github.com/getdokan/dokan/issues/2121
fix: elementor mega menu `z-index` conflict and address line break remove …
> fix: elementor mega menu `z-index` conflict and address line break remove

- includes/functions.php
This PR just adds the Threads social media platform as a Store Socials Option.
Threads can be seen in the 'dashboard/settings/social' section of the dashboard. After adding a threads link, the threads icon and link also appears on the vendors storefront.
> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.
> Add Threads to Store Socials

- includes/functions-dashboard-navigation.php
* https://github.com/getdokan/dokan-wpml/pull/52
* Closes https://github.com/getdokan/dokan-pro/issues/3096
update: Vendor Dashboard settings submenu translation support added
> As a …
> update: Vendor Dashboard settings submenu translation support added

- includes/Vendor/Manager.php
Fix store list filter cacheing with geolocation search.
* Closes https://github.com/getdokan/client-issue/issues/46
* fix:  https://github.com/getdokan/dokan/issues/2165
* Test this issue as mentioned in the issue.
```
**fix:** Fix store list filter cacheing with geolocation search.
```
> As a reviewer, your feedback should be focused on the idea, not the person. …
> Fix: store list filter caching in with geolocation.

- dokan.php
- includes/Registration.php
- includes/Vendor/SetupWizard.php
Fix: The vendor profile progress bar doesn't update if the address is filled from the vendor registration form
* Closes https://github.com/getdokan/dokan-pro/issues/3085
* Reproduce the issue as mentioned in the issue
```
**fix:** Vendor profile progress bar doesn't update if the address is filled from the vendor registration form
```
> As a reviewer, your feedback …
> Fix: The vendor profile progress bar doesn't update if the address is filled from the vendor registration form

- assets/src/less/extra.less
- templates/orders/details.php
Dependency with: [#3213](https://github.com/getdokan/dokan-pro/pull/3213)
* Closes #
```
Fix: Color synchronization issue in vendor dashboard order notes.
``` …
> Fix: Color customizer not sync with vendor's dashboard order buttons.

- includes/Dashboard/Templates/Orders.php
* Full PR Link
* Closes https://github.com/getdokan/dokan/issues/2042
fix: Order Export to CSV on the filtered list not working
> As a reviewer, your feedback should be focused on the …
> fix: Order Export to CSV on filtered list not working

- dokan.php
[#3257](https://github.com/getdokan/dokan-pro/pull/3257)
* Closes #
```
update: Add requires plugin header for dokan.
```
> As a …
> Update: Add requires plugin header for dokan.

- includes/Commission.php
* Full PR Link
* Closes pertial https://github.com/getdokan/dokan/issues/1954
update: `dokan_commission_log_gateway_fee_to_order_note` filter hook added
> As a reviewer, your feedback …
> update: `dokan_commission_log_gateway_fee_to_order_note` filter hook added

- includes/wc-functions.php
[#3252](https://github.com/getdokan/dokan-pro/pull/3252)
* Closes [#3221](https://github.com/getdokan/dokan-pro/issues/3221) | [#3174](https://github.com/getdokan/dokan-pro/issues/3174)
```
Fix: Advertisement product not purchasable for own product purchasing restriction.
```
Video Link: [Link](https://drive.google.com/file/d/1F958bXHocTUUwTNr6GRUkYXjq2J-0vGS/view?usp=sharing)
* KISS: Keep it simple, Sweetie (not …
> Fix: Advertisement product not purchasable for own product purchasing restriction.

- assets/src/js/product-editor.js
- src/admin/pages/VendorAccountFields.vue
Fix html entity showing in product tag selection.
Fix vendor add notification switch in admin dashboard
* Closes #2167 
* Closes https://github.com/getdokan/dokan-pro/issues/3223
* Test as mentioned in the issue.
```
- **fix:** Fix html entity showing in product tag selection in vendor dashboard.
- **fix:** Fix vendor add notification switch in admin dashboard
``` …
> Fix html entity showing in product tag selection and Fix vendor add notification switch in admin dashboard

- includes/Dashboard/Templates/Orders.php
* https://github.com/getdokan/dokan/pull/2195
* Closes https://github.com/getdokan/dokan-pro/issues/2937
* check issue https://github.com/getdokan/dokan-pro/issues/2937
update: Pending Order count added for vendor dashboard orders menu …
> update: Pending Order count added for vendor dashboard Order menu

- assets/src/less/global-admin.less
* https://github.com/getdokan/dokan-pro/pull/3187
* Closes https://github.com/getdokan/dokan-pro/issues/3104.
* Please follow the steps from https://github.com/getdokan/dokan-pro/issues/3104#issuecomment-1990976994
*enhance: Warning message styling for selecting fixed cart discount on admin coupon add edit page*
* …
> 🎨 enhance: Warning message styling for selecting fixed cart discount on admin coupon add edit page

- tests/playwright/e2e/.gitignore
- tests/playwright/e2e/package.json
- tests/playwright/e2e/playwright.config.ts
- tests/playwright/e2e/tests-examples/demo-todo-app.spec.ts
- tests/playwright/e2e/tests/example.spec.ts
* Full PR Link
* Closes #
*Title* …
> playwright test setup

- assets/src/less/general.less
- assets/src/less/products.less
- includes/template-tags.php
Related PR: [Link](https://github.com/getdokan/dokan-pro/pull/3290)
* Closes [#2237](https://github.com/getdokan/dokan/issues/2237)
```
Fix: Store support topic sub-menu displayed a duplicate border.
```
**Need to re-test order listing sub-menu**
* Complicated constructions that need refactoring or comments: code …
> fix: Store support modules menu double border issue.

- templates/withdraw/header.php
Fix withdraw header title string
* Closes #2229
* Closes https://github.com/getdokan/client-issue/issues/111
* Test as mentioned in the issue description.
```
- **fix:** Fix withdraw header title string
```
> As a …
> Fix withdraw header title

- readme.txt
* Full PR Link
* Closes #
*Title* …
> Updated descriptions on readme.txt

- includes/functions.php
* Full PR Link
* Closes #
```md
- **fix:** Translation is not properly loading in some scripts.
```
> As a reviewer, your feedback should be focused on the idea, not the person. Seek to …
> fix: Vue Translation loading from WP Language Directory

- includes/Admin/functions.php
- includes/Order/Manager.php
- includes/Order/MiscHooks.php
- includes/ProductCategory/Hooks.php
- includes/ReverseWithdrawal/Manager.php
- includes/Upgrade/Upgrades/BackgroundProcesses/V_2_8_3_VendorBalance.php
- includes/Upgrade/Upgrades/BackgroundProcesses/V_2_9_4_OrderPostAuthor.php
- includes/Upgrade/Upgrades/V_1_2.php
- includes/Upgrade/Upgrades/V_2_9_13.php
- includes/Upgrade/Upgrades/V_2_9_4.php
- includes/Upgrade/Upgrades/V_3_0_4.php
- includes/Upgrade/Upgrades/V_3_2_12.php
- includes/Upgrade/Upgrades/V_3_3_1.php
- includes/Upgrade/Upgrades/V_3_3_7.php
- includes/functions-compatibility.php
Fix phpcs security warnings.
* Test full plugin errors.
*Title*
> As a reviewer, your feedback …
> Fix plugin phpcs warnings

- includes/Order/Hooks.php
- tests/php/src/DokanTestCase.php
- tests/php/src/Orders/OrderTest.php
Add debug logging for sub order creation #2374 
* Closes #
*Title*
> As a …
> added: test case for Dokan order creation (sub-order)

- src/Dashboard/index.tsx
- src/Routing/index.tsx
* Full PR Link
* Closes #
*Title* …
> Added router context support.

- includes/Analytics/Reports/BaseQueryFilter.php
- includes/Analytics/Reports/Coupons/QueryFilter.php
- includes/Analytics/Reports/OrderType.php
- includes/Analytics/Reports/Orders/QueryFilter.php
- includes/Analytics/Reports/Orders/Stats/DataStore.php
- includes/Analytics/Reports/Orders/Stats/QueryFilter.php
- includes/Analytics/Reports/Stock/QueryFilter.php
- includes/Analytics/Reports/Stock/Stats/WcDataStore.php
- includes/Analytics/Reports/Taxes/Stats/QueryFilter.php
- includes/Install/Installer.php
- tests/php/src/Analytics/Reports/OrderQueryFilterTest.php
- tests/php/src/Analytics/Reports/OrderStatsQueryFilterTest.php
- tests/php/src/Analytics/Reports/OrderStatsScheduleListenerTest.php
- tests/php/src/Analytics/Reports/ProductQueryFilterTest.php
- tests/php/src/Analytics/Reports/ProductStatsQueryFilterTest.php
- tests/php/src/Analytics/Reports/ReportTestCase.php
- tests/php/src/Analytics/Reports/StockProductQueryFilterTest.php
- tests/php/src/Analytics/Reports/StockStatsQueryFilterTest.php
* Full PR Link
* Closes #
*Title* …
> Rename seller to vendor

- includes/Upgrade/Upgrades.php
- includes/Upgrade/Upgrades/BackgroundProcesses/V_3_14_0_UpdateCommissions.php
- includes/Upgrade/Upgrades/V_3_14_0.php
* Full PR Link
* Closes #
*Title* …
> Fix commission upgrade version

- docs/frontend/components.md
- docs/frontend/dataviews.md
- docs/frontend/filter.md
- docs/frontend/hooks.md
- docs/frontend/sortable-list.md
- docs/frontend/utilities.md
- src/components/PriceHtml.tsx
- src/components/dataviews/DataViewTable.tsx
- src/components/sortable-list/index.tsx
- src/dashboard/Withdraw/RequestList.tsx
- src/dashboard/Withdraw/RequestWithdrawBtn.tsx
- src/dashboard/Withdraw/WithdrawRequests.tsx
- src/dashboard/Withdraw/index.tsx
- src/hooks/index.tsx
- src/utils/Bootstrap.js
- webpack.config.js
[#4169](https://github.com/getdokan/dokan-pro/pull/4169)
* Closes #
*Title*
> …
> enhance: Update dokan src package root name.

- assets/src/js/helper.js
- includes/Abstracts/DokanRESTBaseController.php
- includes/Abstracts/DokanRESTCustomerController.php
- includes/Abstracts/DokanRESTVendorController.php
- includes/Commission/Upugrader/Update_Category_Commission.php
- includes/Commission/Upugrader/Update_Product_Commission.php
- includes/Commission/Upugrader/Update_Vendor_Commission.php
- includes/Dashboard/Templates/Settings.php
- includes/ProductStatusRollback.php
- includes/Widgets/FilterByAttributes.php
- includes/functions-dashboard-navigation.php
- includes/functions.php
- templates/products/edit-product-single.php
- templates/products/products-listing-row.php
Replace `DOKAN_PRO_SINCE` with corresponding versions.
* https://github.com/getdokan/dokan/pull/2567
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/273
* 🚫No test needed
* 🚫No change log needed
> Replace `DOKAN_PRO_SINCE` with corresponding versions.

- deprecated/Singleton.php
- deprecated/class-abstract-class-dokan-background-processes.php
- deprecated/class-abstrct-dokan-rest-store-controller.php
- deprecated/class-dokan-email.php
- deprecated/class-dokan-rest-controller.php
- deprecated/class-dokan-rest-product-controller.php
- deprecated/class-dokan-rest-store-controller.php
- deprecated/class-dokan-seller-setup-wizard.php
- deprecated/class-dokan-store-category-walker.php
- deprecated/class-dokan-store-location-widget.php
- deprecated/class-dokan-template-dashboard.php
- deprecated/class-dokan-template-products.php
- deprecated/class-dokan-template-settings.php
- deprecated/class-dokan-vendor.php
- deprecated/class-dokan-withdraw.php
- deprecated/deprecated-classes.php
- deprecated/deprecated-functions.php
- deprecated/deprecated-hooks.php
- includes/Abstracts/DokanRESTBaseController.php
- includes/Abstracts/DokanRESTCustomerController.php
- includes/Abstracts/DokanRESTVendorController.php
> Revert "V4: Remove deprecated files"

- src/dashboard/index.tsx
* Full PR Link
* Closes #
*Title* …
> Fix Tooltip Layout

- base-tailwind.config.js
- src/base-tailwind.scss
- src/components/modals/DokanModal.tsx
- src/layout/Header.tsx
* Full PR Link
* Closes #
*Title* …
> Fix: compatibility support color classes

- src/dashboard/withdraw/PaymentDetails.tsx
- src/dashboard/withdraw/PaymentMethods.tsx
- src/dashboard/withdraw/RequestList.tsx
- src/dashboard/withdraw/RequestWithdrawBtn.tsx
- src/dashboard/withdraw/WithdrawRequests.tsx
- src/dashboard/withdraw/index.tsx
* https://github.com/getdokan/dokan-pro/pull/4316
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/494
> Compatible withdraw with color pallet.

- includes/Assets.php
- includes/Dashboard/Templates/NewDashboard.php
* Full PR Link
* Closes # https://github.com/getdokan/plugin-internal-tasks/issues/498
*Title*
* …
> refactor: wc admin script

- includes/Assets.php
* Full PR Link
* Closes #
*Title* …
> fix: WC admin script registration

- docs/frontend/components.md
- src/components/Upload.tsx
- src/components/index.tsx
* Full PR Link
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/510
*Title*
* …
> Added media upload components

- src/dashboard/index.tsx
- src/utilities/hexToHls.ts
- src/utilities/index.ts
* Full PR Link
* Closes #
*Title* …
> update: Generate dokan Ui colors variant for primary and assign variable

- docs/frontend/back-button.md
- includes/Assets.php
- package.json
- src/dashboard/index.tsx
- src/layout/Header.tsx
- src/layout/index.tsx
- webpack-entries.js
https://github.com/getdokan/dokan-pro/pull/4332
* Closes #
*Title*
> As a …
> enhance: Introduce `Lucide` icon package for reactive frontend.

- src/Status/Status.tsx
- src/hooks/useCurrentUser.ts
- src/hooks/usePermission.ts
- src/routing/index.tsx
* Full PR Link
* Closes #
*Title* …
> fix: `useCurrentUser`, `usePermission` hook and status page layout condition

- src/layout/403.tsx
- src/layout/404.tsx
* Full PR Link
* Closes #
*Title*
> As …
> fix: remove unnecessary width class from error page components

- includes/Assets.php
- webpack.config.js
* https://github.com/getdokan/dokan-pro/pull/4340
* Closes #
*Title*
> As a …
> fix: `dokan.hooks` override.

- src/base-tailwind.scss
- src/utilities/Truncate.ts
- src/utilities/index.ts
> Override WP component button hover color. Added word truncate utility method.

- webpack-dependency-mapping.js
- webpack-entries.js
- webpack.config.js
* Full PR Link
* Closes #
*Title* …
> Fix: global object props naming to expose in window

- docs/frontend/dokan-modal.md
- src/base-tailwind.scss
- src/components/modals/DokanModal.tsx
* Full PR Link
* Closes #
*Title* …
> fix: Update dokan UI standard for react frontend.

- src/components/dataviews/style.scss
* Full PR Link
* Closes #
*Title*
> As …
> fix: action button width issue on dataviews

- includes/Assets.php
- src/components/VisitStore.tsx
- src/components/index.tsx
* Full PR Link
* Closes #
*Title* …
> Added visit store components

- src/components/DateTimeHtml.tsx
- src/dashboard/withdraw/RequestList.tsx
- src/dashboard/withdraw/RequestWithdrawBtn.tsx
- src/dashboard/withdraw/WithdrawRequests.tsx
- src/dashboard/withdraw/tailwind.scss
- src/routing/routes.tsx
> Maintain Dokan UI Standard for v4.0 Withdraw

- includes/Commission/Calculator.php
- includes/Commission/Model/Setting.php
- includes/Commission/OrderLineItemCommission.php
- includes/Commission/Settings/OrderItem.php
- includes/Commission/Strategies/AbstractStrategy.php
- includes/Commission/Strategies/OrderItem.php
- templates/orders/commission-meta-box-html.php
* Full PR Link
* Closes #
*Title* …
> Add & show commission source

- src/dashboard/withdraw/Hooks/useCharge.ts
- src/dashboard/withdraw/RequestWithdrawBtn.tsx
> Fix withdraw invalid charge for invalid withdraw amount.

- src/components/WpDatePicker.tsx
- src/components/index.tsx
* Full PR Link
* Closes #
*Title* …
> Wp date picker added.

- src/base-tailwind.scss
* Full PR Link
* Closes #
*Title* …
> fix: tooltip container `z-index` issue

- src/dashboard/withdraw/Hooks/useWithdrawSettings.ts
- src/dashboard/withdraw/PaymentMethods.tsx
- src/dashboard/withdraw/RequestList.tsx
- src/dashboard/withdraw/WithdrawRequests.tsx
* Full PR Link
* Closes #
*Title* …
> Fix colors

- includes/VendorNavMenuChecker.php
- src/Status/Status.tsx
* Full PR Link
* Closes #
*Title* …
> fix: update dashboard link and remove console logs in status component

- assets/src/less/site-navigation.less
- base-tailwind.config.js
- docs/frontend/color-guidelines.md
- src/admin/dashboard/pages/modules/Card.tsx
- src/base-tailwind.scss
- src/components/Alert.tsx
- src/components/Badge.tsx
- src/components/Button.tsx
- src/components/Link.tsx
- src/components/dataviews/style.scss
- src/components/modals/DokanModal.tsx
This PR updates the components documentation and color guidelines to align with the latest implementation in the codebase. The major changes include:
1. Fixing export types for Button, Badge, Alert, and Link components for better TypeScript support
2. Updating button styles and hover states in Tailwind configuration
3. Updating color guidelines documentation to include status button variables
4. Changing CSS class name variables from `-light` to `-secondary` for consistency
5. Changing DokanModal default button variant from 'danger' to 'primary'
* N/A - This is a standalone documentation and cleanup PR
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/520
1. Review the updated documentation in `docs/frontend/components.md` and `docs/frontend/color-guidelines.md`
2. Check …
> update: Components & Colors Documentation

- includes/functions-dashboard-navigation.php
* Full PR Link
* Closes: https://github.com/getdokan/plugin-internal-tasks/issues/523
```***Fix:*** Broken issue of menu with sub-menu and counts on vendor dashboard```
* Complicated constructions that need …
> fix: Broken issue of vendor dashboard menu with sub-menu and counts

- base-tailwind.config.js
- src/base-tailwind.scss
* Full PR Link
* Closes #
*Title* …
> fix: update hover colors for secondary and tertiary button styles in Tailwind config

- tests/php/src/Commission/OrderCommissionTest.php
* Full PR Link
* Closes #
*Title* …
> added test cases, commission type from_vendor, shared, with refund,

- includes/Commission/OrderCommission.php
- includes/Order/VendorBalanceUpdateHandler.php
* Full PR Link
* Closes #
*Title* …
> fix: prevent refund adjustment in order commission calculation

- src/components/Button.tsx
* Full PR Link
* Closes #
*Title* …
> fix: simplify className merging in DokanUIButton component

- includes/Commission/Calculator.php
- includes/Commission/Model/Setting.php
- includes/Commission/OrderLineItemCommission.php
- includes/Commission/ProductCommission.php
- includes/Commission/Settings/Vendor.php
- includes/Commission/Strategies/Vendor.php
- tests/php/src/Commission/CommissionCalculatorTest.php
* Full PR Link
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/540
*Title*
* …
> Fix the Setting model

- docs/frontend/env-setup.md
* Full PR Link
* Closes #
*Title* …
> docs: add environment setup documentation for Dokan Pro

- src/dashboard/withdraw/RequestWithdrawBtn.tsx
- src/utilities/Accounting.ts
* Full PR Link
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/548
*Title*
* …
> fix: add withCurrencySymbol utility for consistent currency formatting in withdrawal component

- src/dashboard/withdraw/RequestWithdrawBtn.tsx
* Full PR Link
* Closes https://github.com/getdokan/dokan/pull/2702
*Title*
> …
> fix: align buttons to the right in RequestWithdrawBtn component

- src/base-tailwind.scss
- src/components/WpDatePicker.tsx
* Full PR Link
* Closes #
*Title* …
> Fix:simple input UI

- includes/Order/Admin/Hooks.php
- templates/orders/commission-meta-box-html.php
* Full PR Link
* Closes #https://github.com/getdokan/plugin-internal-tasks/issues/552
*Title*
* …
> fix: remove commission meta box extra query

- includes/Order/VendorBalanceUpdateHandler.php
* Full PR Link
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/550
*Title*
* …
> fix: update vendor earning calculation in order listing

- includes/Rewrites.php
* Full PR Link
* Closes #
*Title* …
> fix: simplify rewrite rules flashing condition

- includes/Admin/Notices/UpgradeToV4.php
* https://github.com/getdokan/dokan-pro/pull/4379
* Closes #
*Title*
> As a …
> update: Dokan Pro upgrade notice to version 4.0.0

- src/vendor-dashboard/reports/index.js
* Full PR Link
* Closes #
*Title* …
> fix: oppos! error and improved readability and structure

- src/layout/500.tsx
* Full PR Link
* Closes #
*Title* …
> fix: adjust InternalErrorIcon width for better alignment in error display

- includes/Commission/OrderCommission.php
- includes/Order/VendorBalanceUpdateHandler.php
- src/admin/dashboard/pages/setup-guide/Elements/Fields/Commission/CategoryBasedCommission.tsx
* Full PR Link
* Closes #
*Title* …
> fix: add hooks for tax refunded calculation in OrderCommission

- tests/pw/pages/basePage.ts
- tests/pw/tests/e2e/menuManager.spec.ts
* Full PR Link
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/837
*Title*
* …
> fix: Menu Manager activation test failed for WooCommerce Subscriptions missing.

- tests/pw/pages/commissionPage.ts
- tests/pw/pages/selectors.ts
- tests/pw/tests/e2e/commission.spec.ts
- Enhanced the `setCommissionOnDokanSetupWizard` method to handle success scenarios and streamline the setup process.
- Updated selectors for the Dokan setup wizard and commission meta box for improved accuracy and maintainability.
- Added comments and skipped tests for scenarios needing fixes related to the commission meta box visibility.
* Full PR Link
* Closes #
*Title*
* Bad naming: make sure you would understand your code if you read it a few months from …
> Fix/commission feature tests cases 

- tests/pw/pages/vendorVerificationsPage.ts
- tests/pw/tests/e2e/vendorVerifications.spec.ts
…zard.
* Full PR Link
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/862
*Title* …
> fix: Update vendor verification methods visibility tests for setup wizard.

- tests/pw/tests/e2e/productsDetailsAuction.spec.ts
* Full PR Link
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/845
*Title*
* …
> fix: vendor can remove auction product category (multiple)

- tests/pw/tests/e2e/setupGuide.spec.ts
* Full PR Link
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/850
*Title*
* …
> fix:  setup guide not found issue

- tests/pw/pages/selectors.ts
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/834
> Fix setup wizard test

- tests/pw/pages/basePage.ts
- tests/pw/pages/vendorAuctionsPage.ts
- tests/pw/pages/vendorPage.ts
- tests/pw/utils/testData.ts
* Full PR Link
* Closes https://github.com/getdokan/plugin-internal-tasks/issues/842
*Title*
* …
> fix: product-advertisemnet test case

- tests/pw/tests/e2e/ai.spec.ts
* Full PR Link
* Closes #
*Title* …
> test: skip Product AI test suite and add tag to product title test
